/**
 * Server instructions for postgres-mcp (PostgreSQL MCP Server).
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions/*.md instead,
 *     then run: npm run generate:instructions
 *
 * Slim instructions are sent to MCP clients during initialization.
 * Detailed help is available on-demand via postgres://help resources.
 * Instructions are dynamically generated based on enabled tool groups
 * and instruction level for token efficiency.
 */

import type { ToolGroup } from '../types/index.js'

/**
 * Instruction detail level for token efficiency
 * - essential: ~150 tokens - Core quick access only (for token-constrained clients)
 * - standard: ~200-300 tokens - + dynamic help pointers for enabled groups
 * - full: ~350-400 tokens - + active groups summary
 */
export type InstructionLevel = 'essential' | 'standard' | 'full'

// =============================================================================
// Composable Instruction Segments
// =============================================================================

/**
 * Core instructions — always included regardless of enabled groups.
 * Contains quick access table, built-in tools, and base help pointer.
 */
const CORE_INSTRUCTIONS = `# postgres-mcp (PostgreSQL MCP Server)

## Quick Access

| Purpose         | Action                     |
| --------------- | -------------------------- |
| Health check    | \`pg_analyze_db_health\` tool |
| Server info     | \`pg_server_version\` tool   |
| Database schema | \`postgres://schema\` resource |
| Audit & Tokens  | \`postgres://audit\` resource  |
| Tool help       | \`postgres://help\` resource   |

## Built-in Tools

\`pg_read_query\`, \`pg_write_query\`, \`pg_list_tables\` — always available.`

/**
 * Code Mode summary — only included when codemode group is enabled.
 * Provides API mapping and sandbox constraints.
 */
const CODE_MODE_INSTRUCTIONS = `
## Code Mode

API: \`pg_group_action\` → \`pg.group.action()\` (e.g., \`pg_jsonb_extract\` → \`pg.jsonb.extract()\`)
Top-level: \`pg.readQuery()\`, \`pg.writeQuery()\`, \`pg.listTables()\`, \`pg.describeTable()\`, \`pg.upsert()\`, etc.
Positional: \`readQuery("SELECT...")\`, \`exists("users", "id=1")\`, \`createIndex("users", ["email"])\`
Discovery: \`pg.help()\` → \`{group: methods[]}\`. \`pg.core.help()\`, \`pg.jsonb.help()\` for group-specific.
Sandbox: No \`setTimeout\`, \`setInterval\`, \`fetch\`, or network access. Use \`pg.core.readQuery()\` for data.`

/**
 * All group keys that have help content (for dynamic help pointer generation).
 */
const HELP_GROUP_KEYS: readonly string[] = ["admin","backup","citext","cron","introspection","jsonb","kcache","ltree","migration","monitoring","partitioning","partman","performance","pgcrypto","postgis","schema","stats","text","transactions","vector"]

/**
 * Build dynamic help pointers listing only the enabled groups.
 */
function buildHelpPointers(groups: Set<ToolGroup>): string {
    const enabledHelpGroups = HELP_GROUP_KEYS.filter((k) => groups.has(k as ToolGroup))
    if (enabledHelpGroups.length === 0) {
        return '\n\nRead `postgres://help` for gotchas and critical usage patterns.'
    }
    return '\n\n## Help Resources\n\n' +
        'Read `postgres://help` for gotchas and critical usage patterns.\n' +
        'Read `postgres://help/{group}` for: ' + enabledHelpGroups.join(', ') + '.'
}

/**
 * Build active groups summary listing enabled group names with tool counts.
 */
function buildActiveGroupsSummary(groups: Set<ToolGroup>, enabledToolCount: number): string {
    const groupList = [...groups].sort().join(', ')
    return `\n\n## Active Tools (${String(enabledToolCount)})\n\nGroups: ${groupList}`
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Generate dynamic instructions based on enabled tool groups and instruction level.
 *
 * Sections are conditionally included based on which tool groups are enabled:
 * - Code Mode → only with `codemode` group
 * - Help group listing → `standard`+ level, only lists enabled groups
 * - Active tools summary → `full` level only
 *
 * @param enabledGroups - Set of enabled tool group names
 * @param level - Instruction detail level (default: 'standard')
 * @param enabledToolCount - Number of enabled tools (for full level summary)
 */
export function generateInstructions(
    enabledGroups: Set<ToolGroup>,
    level: InstructionLevel = 'standard',
    enabledToolCount?: number,
): string {
    // Always start with core instructions
    let instructions = CORE_INSTRUCTIONS

    // Code Mode — only when codemode group is enabled
    if (enabledGroups.has('codemode')) {
        instructions += CODE_MODE_INSTRUCTIONS
    }

    // Essential: minimal help pointer (no group listing)
    // Standard+: dynamic help pointers listing enabled groups
    if (level === 'essential') {
        instructions += '\n\nRead `postgres://help` for gotchas and critical usage patterns.'
    } else {
        instructions += buildHelpPointers(enabledGroups)
    }

    // Full level includes active groups summary
    if (level === 'full' && enabledToolCount !== undefined) {
        instructions += buildActiveGroupsSummary(enabledGroups, enabledToolCount)
    }

    return instructions
}

/**
 * Static instructions for backward compatibility.
 * @deprecated Use generateInstructions() instead for dynamic content
 */
export const INSTRUCTIONS = CORE_INSTRUCTIONS

/**
 * Help content keyed by group name.
 * 'gotchas' is the always-available help (postgres://help).
 * Other keys are tool groups (postgres://help/{group}).
 */
export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([
  ["admin", `# Admin Tools

Core: \`vacuum()\`, \`vacuumAnalyze()\`, \`analyze()\`, \`reindex()\`, \`cluster()\`, \`setConfig()\`, \`reloadConf()\`, \`resetStats()\`, \`cancelBackend()\`, \`terminateBackend()\`, \`appendInsight()\`

- All admin tools support \`schema.table\` format (auto-parsed, embedded schema takes priority over explicit \`schema\` param)
- \`vacuum({ table?, full?, analyze?, verbose? })\`: Without \`table\`, vacuums ALL tables. \`verbose\` output goes to logs. Note: Vacuum timing logic triggers log progress feedback *after* validation execution correctly.
- \`reindex({ target, name?, concurrently? })\`: Targets: 'table', 'index', 'schema', 'database'. \`database\` target defaults to current db when \`name\` omitted
- \`cluster()\`: Without args, re-clusters all previously-clustered tables. If \`index\` is specified, \`table\` is also required.
- \`setConfig({ name, value, isLocal? })\`: \`isLocal: true\` applies only to current transaction
- \`cancelBackend({ pid })\`: Graceful query cancellation—returns \`{success: false}\` for invalid PID (no error thrown)
- \`terminateBackend({ pid })\`: Forceful connection termination—use with caution
- \`appendInsight({ insight })\`: Record a business insight to in-memory memo. Insights are accessible via \`postgres://insights\` resource. Use to record key findings during database analysis. Returns \`{success, insightCount, message}\`

Aliases: \`tableName\`→\`table\`, \`indexName\`→\`index\`, \`param\`/\`setting\`→\`name\`, \`processId\`→\`pid\`, \`text\`→\`insight\`

**Top-Level Aliases**: \`pg.vacuum()\`, \`pg.vacuumAnalyze()\`, \`pg.analyze()\`, \`pg.reindex()\`, \`pg.cluster()\`, \`pg.setConfig()\`, \`pg.reloadConf()\`, \`pg.resetStats()\`, \`pg.cancelBackend()\`, \`pg.terminateBackend()\`, \`pg.appendInsight()\`

**Discovery**: \`pg.admin.help()\` returns \`{methods, methodAliases, examples}\` object

**Response structures**:

- \`vacuum()\` / \`vacuumAnalyze()\`: \`{success, message, table?, schema?, hint?}\` (hint present when verbose: true)
- \`analyze()\`: \`{success, message, table?, schema?, columns?}\`
- \`reindex()\`: \`{success, message}\`
- \`cluster()\`: \`{success, message, table?, index?}\` (table/index present for table-specific cluster)
- \`setConfig()\`: \`{success, message, parameter, value}\`
- \`reloadConf()\` / \`resetStats()\`: \`{success, message}\`
- \`cancelBackend()\` / \`terminateBackend()\`: \`{success, message}\`
- \`appendInsight()\`: \`{success, insightCount, message}\``],
  ["backup", `# Backup Tools

Core: \`dumpTable()\`, \`dumpSchema()\`, \`copyExport()\`, \`copyImport()\`, \`createBackupPlan()\`, \`restoreCommand()\`, \`physical()\`, \`restoreValidate()\`, \`scheduleOptimize()\`, \`auditListBackups()\`, \`auditDiffBackup()\`, \`auditRestoreBackup()\`

Response Structures:

- \`dumpTable\`: \`{ddl, type, note, insertStatements?}\` — \`insertStatements\` only with \`includeData: true\` (separate field from \`ddl\`)
- \`copyExport\`: \`{data, rowCount, truncated?, limit?}\` — \`data\` contains CSV/text content. \`truncated: true\` + \`limit\` when rows returned equals applied limit (indicating more rows likely exist)
- \`copyImport\`: \`{command, stdinCommand, notes}\` — Both file and stdin COPY commands
- \`createBackupPlan\`: \`{strategy: {fullBackup, walArchiving}, estimates}\`
- \`restoreCommand\`: \`{command, warnings?, notes}\` — Warnings when \`database\` omitted
- \`restoreValidate\`: \`{note?, validationSteps: [{step, name, command?, commands?, note?}], recommendations}\` — Top-level \`note\` when \`backupType\` omitted (defaults to pg_dump). Step-level \`note\` for non-command steps
- \`physical\`: \`{command, notes, requirements}\`
- \`scheduleOptimize\`: \`{analysis, recommendation, commands}\`

📦 **AI-Optimized Payloads**: \`copyExport\` limits results to 500 rows by default, and implements a hard 50KB safe payload truncation ceiling to protect context window limits. Use \`limit: 0\` for all rows (which is still bounded by the 50KB limit).

- \`pg_copy_export\`: Use \`query\`/\`sql\` OR \`table\`. ⚠️ If both provided, \`query\` takes precedence with warning. Supports \`schema.table\` format (auto-parsed, takes priority over \`schema\` param). Format: \`csv\` (default, comma-delimited), \`text\` (tab-delimited). Both formats support \`header: true\` (default). ⛔ \`binary\` not supported via MCP—use \`pg_dump_schema\` for binary exports. Default \`limit: 500\` (use \`0\` for all rows). Optional \`delimiter\` to customize
- \`pg_dump_table\`: Returns \`ddl\` + \`insertStatements\` when \`includeData: true\`. Supports sequences (\`type: 'sequence'\`), views (\`type: 'view'\`), and partitioned tables (\`type: 'partitioned_table'\` with \`PARTITION BY\` clause). **PRIMARY KEYS, INDEXES, CONSTRAINTS NOT included**—use \`pg_get_indexes\`/\`pg_get_constraints\`. Supports \`schema.table\` format
- \`pg_dump_schema\`: Generates pg_dump command. Optional \`schema\`, \`table\`, \`filename\`
- \`pg_copy_import\`: Generates COPY FROM command. Supports \`schema.table\` format (auto-parsed, takes priority over \`schema\` param). \`columns\` array, \`filePath\`, \`format\`, \`header\`, \`delimiter\`
- \`pg_restore_command\`: Use \`filename\` (alias for \`backupFile\`). Include \`database\` parameter for complete command. Optional \`schemaOnly\`, \`dataOnly\`
- \`pg_create_backup_plan\`: Generates backup strategy with cron schedule. \`frequency\`: 'hourly'|'daily'|'weekly', \`retention\` count
- \`pg_backup_physical\`: Generates pg_basebackup command. Required \`targetDir\`. \`format\`: 'plain'|'tar' (default: 'tar'), \`checkpoint\`: 'fast'|'spread', \`compress\`: 0-9
- \`pg_restore_validate\`: Generates validation commands. Use \`filename\` (alias for \`backupFile\`). \`backupType\`: 'pg_dump' (default)|'pg_basebackup'
- \`pg_backup_schedule_optimize\`: Analyzes database activity patterns and recommends optimal backup schedule
- \`pg_audit_list_backups\`: Reads \`.snapshot.json.gz\` files from backup dir. Optional \`tool?\`/\`target?\` filters. Returns \`{backups: [{filename, tool, target, schema, timestamp, sizeBytes, rowCount?}], count}\` — requires \`--audit-backup\`. Supports \`compact\` mode (default: \`true\`) to significantly conserve payloads
- \`pg_audit_diff_backup({filename})\`: Shows DDL + \`volumeDrift\` (row/size delta vs. live table). \`volumeDrift\` fields are conditional — only present when data exists. Note: Unanalyzed tables (\`reltuples = -1\`) automatically execute a fallback \`SELECT COUNT(*)\` for accurate data volume tracking. Defaults to \`compact: true\` to bypass redundant full DDL blocks and conserve tokens. Returns \`{ddl, volumeDrift?: {rowCountSnapshot?, rowCountCurrent?, sizeBytesSnapshot?, sizeBytesCurrent?, summary}}\`
- \`pg_audit_restore_backup({filename, dryRun?, restoreAs?, confirm})\`: Transaction-wrapped restore. Use \`dryRun: true\` to preview. \`restoreAs\` creates a side-by-side copy instead of overwriting. ⚠️ \`confirm: true\` is strictly REQUIRED for destructive in-place restores. SERIAL sequences dropped with table — DDL with \`nextval()\` fails on restore; use simple types or recreate sequences first. Returns \`{success, restored, restoreAs?}\`

**Top-Level Aliases**: \`pg.dumpTable()\`, \`pg.dumpSchema()\`, \`pg.copyExport()\`, \`pg.copyImport()\`, \`pg.createBackupPlan()\`, \`pg.restoreCommand()\`, \`pg.restoreValidate()\`, \`pg.physical()\`, \`pg.backupPhysical()\`, \`pg.scheduleOptimize()\`, \`pg.backupScheduleOptimize()\`, \`pg.auditListBackups()\`, \`pg.auditDiffBackup()\`, \`pg.auditRestoreBackup()\``],
  ["citext", `# citext Tools

Core: \`createExtension()\`, \`convertColumn()\`, \`listColumns()\`, \`analyzeCandidates()\`, \`compare()\`, \`schemaAdvisor()\`

- \`pg_citext_create_extension\`: Enable citext extension (idempotent). Returns \`{success, message, usage}\`
- \`pg_citext_convert_column\`: Supports \`schema.table\` format (auto-parsed). ⛔ Only allows text-based columns (text, varchar, character varying). Supports optional \`toType\` parameter for pure \`text\` type conversions (useful for reversion). \`col\` alias for \`column\`. Returns \`{previousType}\` showing original type
- \`pg_citext_list_columns\`: Default \`limit: 100\` (use \`0\` for all). Returns \`{columns: [{table_schema, table_name, column_name, is_nullable, column_default}], count, totalCount, truncated}\`. Optional \`schema\`, \`limit\` filters. Supports \`compact\` mode (default: \`true\`) to structurally omit empty arrays
- \`pg_citext_analyze_candidates\`: Default \`limit: 50\` (use \`0\` for all). Default \`excludeSystemSchemas: true\` filters out extension schemas (cron, topology, partman, tiger) when no \`schema\`/\`table\` filter specified—use \`excludeSystemSchemas: false\` to include all. Returns \`truncated: true\` + \`totalCount\` when results are limited. Scans tables for TEXT/VARCHAR columns matching common patterns (email, username, name, etc.). Optional \`schema\`, \`table\`, \`limit\`, \`excludeSystemSchemas\`, \`patterns\` filters. Returns \`{candidates, count, totalCount, truncated, summary: {highConfidence, mediumConfidence}, recommendation, patternsUsed, excludedSchemas?}\`. Supports \`compact\` mode (default: \`true\`) to structurally omit empty arrays
- \`pg_citext_compare\`: Test case-insensitive comparison. Returns \`{value1, value2, citextEqual, textEqual, lowerEqual, extensionInstalled}\`. Empty strings are handled gracefully natively without throwing validation errors.
- \`pg_citext_schema_advisor\`: Supports \`schema.table\` format (auto-parsed). Analyzes specific table. Returns \`{table, recommendations: [{column, currentType, previousType?, recommendation, confidence, reason}], summary, nextSteps}\`. \`tableName\` alias for \`table\`. Already-citext columns include \`previousType: "text or varchar (converted)"\`

**Discovery**: \`pg.citext.help()\` returns \`{methods, methodAliases, examples}\` object`],
  ["cron", `# Cron Tools (pg_cron)

Core: \`createExtension()\`, \`schedule()\`, \`scheduleInDatabase()\`, \`unschedule()\`, \`alterJob()\`, \`listJobs()\`, \`jobRunDetails()\`, \`cleanupHistory()\`

- \`pg_cron_schedule\`: Schedule a cron job. \`schedule\` supports standard cron (\`0 5 * * *\`) or interval (\`1 second\` to \`59 seconds\`). ⚠️ Interval syntax only works for 1-59 seconds—for 60+ seconds, use cron syntax (e.g., \`* * * * *\` for every minute). Use \`name\`/\`jobName\` for identification. \`command\`/\`sql\`/\`query\` aliases supported. Note: pg_cron allows duplicate job names; use unique names to avoid confusion when unscheduling
- \`pg_cron_schedule_in_database\`: Schedule job in specific database. \`database\`/\`db\` aliases. Optional \`username\`, \`active\` params
- \`pg_cron_unschedule\`: Remove job by \`jobId\` or \`jobName\`. Inactive job failures are handled via \`jobId\` fallback lookups. If both provided, \`jobName\` takes precedence (with warning)
- \`pg_cron_alter_job\`: Modify existing job. Can change \`schedule\`, \`command\`, \`database\`, \`username\`, \`active\`. ⛔ Non-existent jobId returns error
- \`pg_cron_list_jobs\`: List all jobs. Default \`limit: 50\` (use \`0\` for all). Optional \`active\` boolean filter. Returns \`truncated\` + \`totalCount\` when limited. Returns \`hint\` when jobs have no name. Supports \`compact\` mode (default: \`true\`) to structurally omit empty arrays
- \`pg_cron_job_run_details\`: View execution history. Default \`limit: 50\`. Optional \`jobId\`, \`status\` ('running'|'succeeded'|'failed') filters. Returns \`truncated\` + \`totalCount\` when limited. Returns \`summary\` with counts. Supports \`compact\` mode (default: \`true\`) to structurally omit empty arrays
- \`pg_cron_cleanup_history\`: Delete old run records. \`olderThanDays\`/\`days\` param (default: 7). Optional \`jobId\` to target specific job
- \`pg_cron_create_extension\`: Enable pg_cron extension (idempotent). Requires superuser

**Discovery**: \`pg.cron.help()\` returns \`{methods, methodAliases, examples}\` object`],
  ["gotchas", `# postgres-mcp Code Mode

## ⚠️ Critical Gotchas

1. **Transactions**: \`pg.transactions.execute({statements: [{sql: "..."}]})\` auto-commits on success, auto-rollbacks on error. To join existing transaction: \`{transactionId: txId, statements: [...]}\` (no auto-commit, caller controls)
2. **pg_write_query**: ⛔ Throws for SELECT—use \`pg_read_query\` for SELECT statements
3. **pg_upsert/pg_create_table**: \`schema.table\` format auto-parses (e.g., \`'myschema.users'\` → schema: 'myschema', table: 'users')
4. **pg_create_table columns**: \`notNull\`, \`defaultValue\` (string literals auto-quoted; numbers/booleans auto-coerced; \`now()\` → \`CURRENT_TIMESTAMP\`), \`check\`, \`references\` (object or string \`"table(column)"\` syntax)
5. **pg_create_table constraints**: \`constraints\` array only accepts \`{type: 'unique'|'check'}\`. Primary keys: use \`column.primaryKey\` or top-level \`primaryKey: ['col1', 'col2']\`
6. **pg_create_index expression**: Columns can be expressions like \`LOWER(name)\` or \`UPPER(email)\`—auto-detected. ⚠️ Cast syntax (\`::\`) requires raw SQL via \`pg_write_query\`
7. **pg_list_objects type**: Use \`type\` (singular string) or \`types\` (array). Auto-converts: \`{type: 'table'}\` ≡ \`{types: ['table']}\`
8. **pg_object_details**: Accepts: \`name\`, \`objectName\`, \`object\`, or \`table\`. Use \`type\`/\`objectType\` for type hint (supports: table, view, materialized_view, partitioned_table, function, sequence, index)
9. **pg_exists optional WHERE**: \`where\`/\`condition\`/\`filter\` is optional. Without it, checks if table has any rows
10. **pg_describe_table**: Returns columns, foreignKeys, primaryKey, indexes, constraints. For listing ALL database indexes (not table-specific), use \`pg_get_indexes\` without \`table\` param
11. **pg_vector_insert updateExisting**: Uses direct UPDATE (avoids NOT NULL constraint issues vs INSERT mode)
12. **pg_get_indexes without table**: Returns ALL database indexes (potentially large). Use \`table\` param for specific table
13. **pg_upsert/pg_batch_insert RETURNING**: \`returning\` param must be array of column names: \`["id", "name"]\`. ⛔ \`"*"\` wildcard not supported
14. **Small tables**: Optimizer correctly uses Seq Scan for <1000 rows—this is expected behavior
15. **Token Payload Bounds**: Global limit constraints (\`n\`, \`limit\`, \`sanitizeResult\`) are strictly clamped to prevent token bloat, generating typically ~30-41% token reductions.
16. **Structured Errors**: P154 validation replaces legacy \`{success: false}\` failures with explicit \`ValidationError\` exceptions, to strictly prevent underlying Postgres SQL syntax leakage.
## 🔄 Response Structures

| Tool                          | Returns                                                                                                                                     | Notes                                                                                                                                                                                                                                                  |
| ----------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------- | ---------------------------------------------------------------------------------------- |
| \`pg_read_query\`               | \`{rows, rowCount, fields?}\`                                                                                                                 | \`fields\` contains column metadata (name, dataTypeID)                                                                                                                                                                                                   |
| \`pg_write_query\`              | \`{rowsAffected, rows?}\`                                                                                                                     | \`rows\` only with RETURNING clause. DDL statements return \`rowsAffected: 0\`. ⛔ Throws for SELECT                                                                                                                                                       |
| \`pg_upsert\`                   | \`{success, operation, rowsAffected, rows?}\`                                                                                                 | \`operation: 'insert' | 'update'\`. \`rows\` only with RETURNING clause |
| \`pg_batch_insert\`             | \`{success, rowsAffected, rows?}\`                                                                                                            | Empty objects use DEFAULT VALUES. ⚠️ BIGINT > 2^53 loses precision                                                                                                                                                                                     |
| \`pg_create_table\`             | \`{success, table, sql, compositePrimaryKey?}\`                                                                                               | \`table\` = schema-qualified name. \`compositePrimaryKey\` only when composite PK used                                                                                                                                                                     |
| \`pg_drop_table\`               | \`{success, dropped, existed}\`                                                                                                               | \`existed\` indicates whether table was present before drop                                                                                                                                                                                              |
| \`pg_create_index\`             | \`{success, index, indexName, table, sql, ifNotExists?, alreadyExists?, message?}\`                                                           | \`alreadyExists\`/\`message\` only with \`ifNotExists: true\` when index pre-exists                                                                                                                                                                          |
| \`pg_drop_index\`               | \`{success, index, existed, sql}\`                                                                                                            | \`existed\` indicates whether index was present before drop                                                                                                                                                                                              |
| \`pg_truncate\`                 | \`{success, table, cascade, restartIdentity}\`                                                                                                | \`cascade\`/\`restartIdentity\` reflect the options used                                                                                                                                                                                                   |
| \`pg_count\`                    | \`{count: N}\`                                                                                                                                | Use \`params\` for placeholders: \`where: 'id=$1', params: [5]\`. DISTINCT: use \`pg_read_query\`                                                                                                                                                            |
| \`pg_exists\`                   | \`{exists: bool, mode, hint?}\`                                                                                                               | \`params\` for placeholders. \`mode: 'filtered' | 'any_rows'\`                                                                                                                                                                                           |
| \`pg_get_indexes\`              | \`{indexes, count, totalCount?}\`                                                                                                             | Default \`limit: 100\` without \`table\`. Use \`schema\`/\`limit\` to filter. Index objects have \`name\`, \`type\`, \`columns\`                                                                                                                                     |
| \`pg_list_objects\`             | \`{objects, count, totalCount, byType}\`                                                                                                      | Use \`limit\` to cap results, \`type\`/\`types\` to filter                                                                                                                                                                                                   |
| \`pg_object_details\`           | \`{name, schema, type, returnType?, ...}\`                                                                                                    | Functions: \`returnType\` alias. Views/Mat. views: \`definition\`. Tables: equivalent to \`pg_describe_table\` (columns, primaryKey, indexes, constraints, foreignKeys)                                                                                      |
| \`pg_analyze_db_health\`        | \`{cacheHitRatio, databaseSize, tableStats, unusedIndexes, tablesNeedingVacuum, connections, bloat, isReplica, overallScore, overallStatus}\` | \`cacheHitRatio\`: \`{ratio, heap, index, status}\`. \`overallStatus\`: \`healthy | needs_attention | critical\`. Optional sections via \`includeIndexes\`, \`includeVacuum\`, \`includeConnections\` |
| \`pg_describe_table\`           | \`{name, schema, type, owner?, rowCount, columns, primaryKey, indexes, constraints, foreignKeys}\`                                            | Columns include \`notNull\`, optional \`primaryKey\`, \`defaultValue\`, \`foreignKey\` (omitted when false/null). \`constraints\` includes PK, UNIQUE, CHECK, NOT NULL. ⚠️ \`rowCount: -1\` = stale/missing statistics (run ANALYZE on the table). Small tables (<~50 rows) may show -1 until first ANALYZE |
| \`pg_analyze_query_indexes\`    | \`{plan, issues, recommendations}\`                                                                                                           | \`verbosity\`: 'summary' (default) or 'full'. Summary mode returns condensed plan                                                                                                                                                                        |
| \`pg_list_tables\`              | \`{tables, count, totalCount, truncated?, hint?}\`                                                                                            | Use \`schema\` to filter, \`limit\` to cap results, \`exclude\` to hide extension schemas (e.g., \`['cron', 'topology', 'partman']\`)                                                                                                                          |
| List operations               | \`{items, count}\`                                                                                                                            | Access via \`result.tables\`, \`result.views\`, etc.                                                                                                                                                                                                       |
| \`pg_jsonb_agg groupBy\`        | \`{result: [{group_key, items}], count, grouped: true}\`                                                                                      | Without groupBy: \`{result: [...], count, grouped: false}\`                                                                                                                                                                                              |
| \`pg_vector_aggregate\`         | \`{average_vector, count}\` or \`{groups: [{group_key, average_vector, count}]}\`                                                               | Without/with \`groupBy\`                                                                                                                                                                                                                                 |
| \`pg_index_stats\`              | \`{indexes, count, truncated?, totalCount?}\`                                                                                                 | Default 50 rows. Use \`limit: 0\` for all                                                                                                                                                                                                                |
| \`pg_table_stats\`              | \`{tables, count, truncated?, totalCount?}\`                                                                                                  | Default 50 rows. Use \`limit: 0\` for all                                                                                                                                                                                                                |
| \`pg_vacuum_stats\`             | \`{tables, count, truncated?, totalCount?}\`                                                                                                  | Default 50 rows. Use \`limit: 0\` for all                                                                                                                                                                                                                |
| \`pg_stat_statements\`          | \`{statements, count, truncated?, totalCount?}\`                                                                                              | Default 20 rows. \`orderBy\` supported                                                                                                                                                                                                                   |
| \`pg_query_plan_stats\`         | \`{queryPlanStats, count, truncated?, totalCount?}\`                                                                                          | Default 20 rows. \`truncateQuery: 0\` for full text                                                                                                                                                                                                      |
| \`pg_stat_activity\`            | \`{connections, count, backgroundWorkers}\`                                                                                                   | \`includeIdle: true\` to include idle connections. \`backgroundWorkers\` = count of background worker processes                                                                                                                                            |
| \`pg_locks\`                    | \`{locks}\`                                                                                                                                   | \`showBlocked: true\` switches to blocked/blocking pid format                                                                                                                                                                                            |
| \`pg_bloat_check\`              | \`{tables, count}\`                                                                                                                           | Tables with \`live_tuples\`, \`dead_tuples\`, \`dead_pct\`                                                                                                                                                                                                   |
| \`pg_cache_hit_ratio\`          | \`{heap_read, heap_hit, cache_hit_ratio}\`                                                                                                    | All fields nullable (0 tables = null). Flat response, differs from \`pg_analyze_db_health.cacheHitRatio\`                                                                                                                                                |
| \`pg_seq_scan_tables\`          | \`{tables, count, minScans, hint, truncated?, totalCount?}\`                                                                                  | Default 50 rows. \`minScans\` default: 10                                                                                                                                                                                                                |
| \`pg_connection_pool_optimize\` | \`{current, config, waitEvents, recommendations}\`                                                                                            | No params needed                                                                                                                                                                                                                                       |
| \`pg_performance_baseline\`     | \`{name, timestamp, metrics}\`                                                                                                                | \`metrics\`: \`cache\`, \`tables\`, \`indexes\`, \`connections\`, \`databaseSize\`                                                                                                                                                                                 |
| \`pg_duplicate_indexes\`        | \`{duplicateIndexes, count, hint, truncated?, totalCount?}\`                                                                                  | Default 50 rows. \`duplicate_type\`: EXACT_DUPLICATE, OVERLAPPING, SUBSET                                                                                                                                                                                |
| \`pg_query_plan_compare\`       | \`{query1, query2, analysis, fullPlans, compact?}\`                                                                                                     | \`analysis.costDifference\` + \`recommendation\`. Pass \`compact: true\` to suppress massive \`fullPlans\` JSON.                                                                                                                                                                                                           |
| \`pg_unused_indexes\`           | \`{unusedIndexes, count, hint, truncated?, totalCount?}\`                                                                                     | Default 20 rows. \`summary: true\` → \`{summary, bySchema, totalCount}\`                                                                                                                                                                                   |
| All tools                     | \`_meta.tokenEstimate\` in \`content[].text\`                                                                                                   | Every response wraps result with \`{ ...result, _meta: { tokenEstimate: N } }\`. Token cost heuristic: ~4 bytes/token (~4 chars). \`structuredContent\` stays schema-pure (no \`_meta\`). Code Mode adds \`metrics.tokenEstimate\` instead.                    |

💡 **Token Optimization**: Monitor \`_meta.tokenEstimate\` on responses. For multi-step tasks or large result sets, use **Code Mode** (\`pg_execute_code\`) to execute logic server-side. Check \`postgres://audit\` for a full session token summary.

## API Mapping

\`pg_group_action\` → \`pg.group.action()\` (group prefixes dropped: \`pg_jsonb_extract\` → \`pg.jsonb.extract()\`)

**Top-Level Core Aliases**: All starter tools available directly: \`pg.readQuery()\`, \`pg.writeQuery()\`, \`pg.listTables()\`, \`pg.describeTable()\`, \`pg.createTable()\`, \`pg.dropTable()\`, \`pg.count()\`, \`pg.exists()\`, \`pg.upsert()\`, \`pg.batchInsert()\`, \`pg.truncate()\`, \`pg.createIndex()\`, \`pg.dropIndex()\`, \`pg.getIndexes()\`, \`pg.listObjects()\`, \`pg.objectDetails()\`, \`pg.listExtensions()\`, \`pg.analyzeDbHealth()\`, \`pg.analyzeQueryIndexes()\`, \`pg.analyzeWorkloadIndexes()\`

**Positional args work**: \`readQuery("SELECT...")\`, \`exists("users", "id=1")\`, \`createIndex("users", ["email"])\`

**Discovery**: \`pg.help()\` returns \`{group: methods[]}\` mapping (e.g., \`{core: ['readQuery', ...], jsonb: [...]}\`). \`pg.core.help()\`, \`pg.jsonb.help()\` for group-specific methods.

## Format Auto-Resolution

- **Schema.Table**: \`'public.users'\` auto-parses to \`{schema: 'public', table: 'users'}\`
- **JSONB Paths**: Both \`'a.b.c'\` (string) and \`['a','b','c']\` (array) work. Use array for literal dots: \`["key.with.dots"]\`
- **Aliases**: Common parameter variations resolve automatically (e.g., \`query\`/\`sql\`, \`table\`/\`tableName\`)

---

## Code Mode Sandbox

No \`setTimeout\`, \`setInterval\`, \`fetch\`, or network access. Use \`pg.core.readQuery()\` for data access.

📊 **Metrics Note**: \`memoryUsedMb\` measures heap delta (end - start). Negative values indicate memory freed during execution (e.g., GC ran). \`metrics.tokenEstimate\` = estimated token cost of the sandbox result (~4 bytes/token).`],
  ["introspection", `# Introspection Tools

Code Mode: \`pg.introspection.*\` — 6 read-only tools for schema analysis.
Core: \`dependencyGraph()\`, \`topologicalSort()\`, \`cascadeSimulator()\`, \`schemaSnapshot()\`, \`constraintAnalysis()\`, \`migrationRisks()\`

**Schema Analysis (6 tools):**

- \`pg_dependency_graph\`: FK dependency graph with cycle detection, row counts, edge annotations (CASCADE, RESTRICT, SET NULL, SET DEFAULT, NO ACTION). Params: \`schema?\`, \`includeRowCounts?\` (default: true), \`excludeExtensionSchemas?\` (default: true, excludes cron/topology/tiger/tiger_data)
- \`pg_topological_sort\`: Safe DDL execution order via Kahn's algorithm. \`direction: 'create'\` (default) = dependencies first; \`direction: 'drop'\` = dependents first. \`excludeExtensionSchemas?\` (default: true). Self-referencing FKs are filtered (don't affect ordering)
- \`pg_cascade_simulator\`: Simulates DELETE/DROP/TRUNCATE impact with cascade path tracing. \`operation\`: 'DELETE' (default), 'DROP', 'TRUNCATE'. ⚠️ DROP/TRUNCATE force-cascade regardless of FK ON DELETE rule → always \`severity: 'critical'\` when dependent tables exist. Returns \`{sourceTable, operation, affectedTables, severity, stats}\`. Stats include \`blockingActions\` (NO ACTION + RESTRICT FKs that would prevent the operation)
- \`pg_schema_snapshot\`: Full schema snapshot in one call. \`sections?\`: \`['tables','views','indexes','constraints','functions','triggers','sequences','types','extensions']\` to limit output. \`compact?\`: \`true\` (default) omits per-column details to conserve payload (use \`pg_describe_table\` to drill down) and structurally omits 0-value keys and empty arrays from the \`stats\` telemetry block. \`excludeExtensionSchemas?\` (default: true): excludes cron, topology, tiger schemas. \`schema?\`: filter to specific schema. Returns \`{snapshot, stats, generatedAt, compact?}\`
- \`pg_constraint_analysis\`: Identifies constraint issues. \`checks?\`: \`['redundant','missing_fk','missing_not_null','missing_pk','unindexed_fk']\`. Returns \`{findings, summary}\`
- \`pg_migration_risks\`: Static DDL risk assessment. ⚠️ Does NOT validate object existence—analyzes SQL patterns only. Returns \`{risks, summary}\`

**Discovery**: \`pg.introspection.help()\` returns \`{methods, methodAliases, examples}\``],
  ["jsonb", `# JSONB Tools

- \`pg_jsonb_extract\`: Returns null if path doesn't exist
- \`pg_jsonb_insert\`: Index -1 inserts BEFORE last element; use \`insertAfter: true\` to append. ⚠️ Use array format \`[-1]\` not string \`"[-1]"\` for negative indices
- \`pg_jsonb_set\`: \`createMissing=true\` creates full nested paths; initializes NULL columns to \`{}\`. Empty path (\`''\` or \`[]\`) replaces entire column value
- \`pg_jsonb_strip_nulls\`: ⚠️ Requires \`where\`/\`filter\` clause—write operations must be targeted. Use \`preview: true\` to see changes first
- \`pg_jsonb_agg\`: Supports AS aliases in select: \`["id", "metadata->>'name' AS name"]\`. ⚠️ \`->>\` returns text—use \`->\` to preserve JSON types
- \`pg_jsonb_object\`: Use \`data\`, \`object\`, or \`pairs\` parameter: \`{data: {name: "John", age: 30}}\`. Also accepts parallel arrays (\`{keys: ["n"], values: [1]}\`). ⚠️ Must provide at least one entry; empty configurations throw validation errors. Array escaping is handled safely in Code Mode without parallel array leakage. Returns \`{object: {...}}\`
- \`pg_jsonb_normalize\`: \`flatten\` doesn't descend into arrays; \`keys\` returns text (use \`pairs\` for JSON types). Standardizes validation requiring either (\`table\` + \`column\`) OR \`json\` payload.
- \`pg_jsonb_stats\`: Returns column-level statistics. \`topKeysLimit\` controls key count (default: 20). ⚠️ \`typeDistribution\` null type = SQL NULL columns. Use \`sqlNullCount\` for explicit count
- \`pg_jsonb_pretty\`: Two modes: (1) Pass raw JSON via \`json\` or \`value\` param—formats locally. (2) Pass \`table\` + \`column\`—uses native \`jsonb_pretty()\`. Table mode returns standardized \`count\` and defaults to \`limit: 10\`. Returns \`{formatted}\` or \`{rows, count}\`
- \`pg_jsonb_validate_path\`: Returns \`{success: true, valid: true}\` for valid paths starting with \`$\`. Throws explicit \`ValidationError\` with \`$\`-prefix hints for invalid paths — use \`$.key\` not \`key\`.
- 🛡️ **Validation Consistency**: \`pg_jsonb_typeof\`, \`pg_jsonb_keys\`, and \`pg_jsonb_path_query\` share standard parameter validation. String literal validations natively enforce explicit JSON parsing to prevent text injection.
- ⛔ **Object-only tools**: \`diff\`, \`merge\`, \`keys\`, \`indexSuggest\`, \`securityScan\`, \`stats\` require JSONB objects, throw descriptive errors for arrays
- ⛔ **Array-only tools**: \`insert\` requires JSONB arrays, throws errors for objects
- 📝 \`normalize\` modes: \`pairs\`/\`keys\`/\`flatten\` for objects; \`array\` for arrays
- 📦 **AI-Optimized Payloads**: \`contains\` and \`pathQuery\` default to 100 results. Returns \`truncated\` + \`totalCount\` when capped. Use \`limit: 0\` for all rows

**Top-Level Aliases**: \`pg.jsonbExtract()\`, \`pg.jsonbSet()\`, \`pg.jsonbInsert()\`, \`pg.jsonbDelete()\`, \`pg.jsonbContains()\`, \`pg.jsonbPathQuery()\`, \`pg.jsonbAgg()\`, \`pg.jsonbObject()\`, \`pg.jsonbArray()\`, \`pg.jsonbKeys()\`, \`pg.jsonbStripNulls()\`, \`pg.jsonbTypeof()\`, \`pg.jsonbValidatePath()\`, \`pg.jsonbMerge()\`, \`pg.jsonbNormalize()\`, \`pg.jsonbDiff()\`, \`pg.jsonbIndexSuggest()\`, \`pg.jsonbSecurityScan()\`, \`pg.jsonbStats()\`, \`pg.jsonbPretty()\``],
  ["kcache", `# pg_stat_kcache Tools

Core: \`createExtension()\`, \`queryStats()\`, \`topCpu()\`, \`topIo()\`, \`databaseStats()\`, \`resourceAnalysis()\`, \`reset()\`

- \`pg_kcache_query_stats\`: Default \`limit: 20\` (use \`0\` for all). Returns \`truncated\` + \`totalCount\` when limited. \`orderBy\`: 'total_time' (default), 'cpu_time', 'reads', 'writes'. \`queryPreviewLength\`: chars for query preview (default: 100, max: 500, 0 for full). ⛔ 'calls' NOT valid for orderBy—use \`minCalls\` param
- \`pg_kcache_resource_analysis\`: Default \`limit: 20\` (use \`0\` for all). Returns \`truncated\` + \`totalCount\` when limited. \`minCalls\`, \`queryPreviewLength\` supported. Classifies queries as 'CPU-bound', 'I/O-bound', or 'Balanced'
- \`pg_kcache_top_cpu\`: Top CPU-consuming queries. \`limit\` param (default: 10). \`queryPreviewLength\`: chars for query preview (default: 100, max: 500, 0 for full). Returns \`truncated\` + \`totalCount\` when limited
- \`pg_kcache_top_io\`: \`type\`/\`ioType\` (alias): 'reads', 'writes', 'both' (default). \`limit\` param (default: 10). \`queryPreviewLength\`: chars for query preview (default: 100, max: 500, 0 for full). Returns \`truncated\` + \`totalCount\` when limited
- \`pg_kcache_database_stats\`: Aggregated CPU/IO stats per database. Optional \`database\` param to filter specific db
- \`pg_kcache_reset\`: Resets pg_stat_kcache AND pg_stat_statements statistics`],
  ["ltree", `# ltree Tools

Core: \`createExtension()\`, \`query()\`, \`match()\`, \`subpath()\`, \`lca()\`, \`listColumns()\`, \`convertColumn()\`, \`createIndex()\`

- \`pg_ltree_create_extension\`: Enable ltree extension (idempotent). Returns \`{success, message}\`
- \`pg_ltree_query\`: Query hierarchical relationships. Supports \`schema.table\` format (auto-parsed). \`mode\`/\`type\`: 'ancestors', 'descendants' (default), 'exact'. Returns \`{results, count, path, mode, isPattern}\`. ⚠️ Validates column is ltree type—returns clear error for non-ltree columns
- \`pg_ltree_match\`: Match paths using lquery pattern syntax (\`*\`, \`*{1,2}\`, \`*.label.*\`). Supports \`schema.table\` format. \`pattern\`/\`lquery\`/\`query\` aliases. Returns \`{results, count, pattern}\`
- \`pg_ltree_subpath\`: Extract portion of ltree path. \`offset\`/\`start\`/\`from\` and \`length\`/\`len\` aliases. Negative \`offset\` counts from end. ⚠️ Returns \`{success: false, error, pathDepth}\` for invalid offset (validated before PostgreSQL call)
- \`pg_ltree_lca\`: Find longest common ancestor of multiple paths. Requires \`paths\` array (min 2). Returns \`{longestCommonAncestor, hasCommonAncestor: bool, paths}\`
- \`pg_ltree_list_columns\`: List all ltree columns in database. Optional \`schema\` filter. Returns \`{columns: [{table_schema, table_name, column_name, is_nullable, column_default}], count}\`
- \`pg_ltree_convert_column\`: Convert TEXT column to ltree. Supports \`schema.table\` format. \`col\` alias for \`column\`. Returns \`{previousType}\`. ⚠️ When views depend on column, returns \`{success: false, dependentViews, hint}\`—drop/recreate views manually
- \`pg_ltree_create_index\`: Create GiST index on ltree column. Supports \`schema.table\` format. Auto-generates index name if \`indexName\` omitted. Returns \`{indexName, indexType: 'gist', alreadyExists?}\`

**Discovery**: \`pg.ltree.help()\` returns \`{methods, methodAliases, examples}\` object. Top-level aliases available: \`pg.ltreeQuery()\`, \`pg.ltreeMatch()\`, etc.`],
  ["migration", `# Migration Tools

Code Mode: \`pg.migration.*\` — 6 tools for schema migration tracking and management.
Core: \`init()\`, \`record()\`, \`apply()\`, \`rollback()\`, \`history()\`, \`status()\`

- \`pg_migration_init\`: Initialize/verify \`_mcp_schema_versions\` tracking table (idempotent). Returns \`{success, tableCreated, tableName, existingRecords}\`
- \`pg_migration_record\`: Record a migration with SHA-256 hash dedup. ⚠️ Records metadata only—does NOT execute the SQL (status: 'recorded'). Use \`pg_migration_apply\` instead for complete migrations (status: 'applied'). Params: \`version\`, \`description?\`, \`migrationSql\`, \`rollbackSql?\`, \`sourceSystem?\`. Returns \`{success, record}\`
- \`pg_migration_apply\`: Execute migration SQL and record it atomically in a single transaction. On failure, rolls back and records status as 'failed'. Same params as \`pg_migration_record\`. Returns \`{success, record}\` or \`{success: false, error}\`
- \`pg_migration_rollback\`: Execute stored rollback SQL in a transaction. \`dryRun: true\` previews without executing (default: \`false\` — executes immediately). Lookup by \`id\` or \`version\`. Returns \`{success, dryRun, rollbackSql, record}\`
- \`pg_migration_history\`: Query migration history with \`status?\` ('applied'|'recorded'|'rolled_back'|'failed'), \`sourceSystem?\`, \`limit?\`, \`offset?\`. Returns \`{records, total, limit, offset}\`
- \`pg_migration_status\`: Aggregate dashboard. Returns \`{initialized, latestVersion, counts, sourceSystems}\`

**Discovery**: \`pg.migration.help()\` returns \`{methods, methodAliases, examples}\``],
  ["monitoring", `# Monitoring Tools

Core: \`databaseSize()\`, \`tableSizes()\`, \`connectionStats()\`, \`showSettings()\`, \`capacityPlanning()\`, \`uptime()\`, \`serverVersion()\`, \`recoveryStatus()\`, \`replicationStatus()\`, \`resourceUsageAnalyze()\`, \`alertThresholdSet()\`

- \`databaseSize()\`: Returns \`{success: true, bytes: number, size: string}\`. Optional \`database\` param for specific db
- \`tableSizes({ limit?, schema?, pattern? })\`: Clamped to a maximum of 100 rows to prevent unmanageable token bloat. Default limit 10. Accepts \`pattern\`, \`table\`, or \`name\` for table wildcard matching (e.g., \`%orders%\` or exact). Returns \`{success: true, tables: [...], count, truncated?, totalCount?}\`. \`truncated: true\` + \`totalCount\` when limited. Use \`limit: 0\` for up to 100 rows (maximum allowed)
- \`connectionStats({ database? })\`: Requires P154 existence checks. Returns \`{success: true, byDatabaseAndState, totalConnections: number, maxConnections: number}\`
- \`showSettings({ setting?, limit? })\`: Clamped to a maximum of 100 rows to prevent unmanageable token bloat. Default limit 50 when no pattern. Accepts \`pattern\`, \`setting\`, \`name\`, or \`like\`. Exact names auto-match; \`%\` for LIKE patterns
- \`capacityPlanning({days: 90})\`: \`days\` = \`projectionDays\`. Returns \`{success: true, current, growth, projection, recommendations}\` with numeric fields. ⛔ Negative days rejected
- \`uptime()\`: Returns \`{success: true, start_time: string, uptime: {days, hours, minutes, seconds, milliseconds}}\`
- \`serverVersion()\`: Returns \`{success: true, full_version: string, version: string, version_num: number}\`
- \`recoveryStatus()\`: Returns \`{success: true, in_recovery: boolean, last_replay_timestamp: string|null}\`
- \`replicationStatus()\`: Returns \`{success: true, role: 'primary'|'replica', replicas: [...]}\` for primary, or \`{success: true, role: 'replica', replay_lag, ...}\` for replica
- \`resourceUsageAnalyze()\`: Returns \`{success: true, backgroundWriter, checkpoints, connectionDistribution, bufferUsage, activity, analysis}\` with all counts as numbers
- \`alertThresholdSet({metric, warningThreshold?, criticalThreshold?})\`: Enforces strict threshold percentage bounds (0-100%, rejecting empty string or NaN evasions). Returns recommended mapping or sets them. Valid metrics: connection_usage, cache_hit_ratio, replication_lag, dead_tuples, long_running_queries, lock_wait_time

📦 **AI-Optimized Payloads**: Tools return limited results by default to reduce context size:

- \`tableSizes({ limit? })\`: Default 10 rows. Returns \`truncated: true\` + \`totalCount\` when limited. Use \`limit: 0\` for up to 100 rows (maximum allowed)
- \`showSettings({ limit? })\`: Default 50 rows when no pattern specified. Use \`limit: 0\` for up to 100 rows (maximum allowed) or specify a pattern

Aliases: \`tables\`→\`tableSizes\`, \`connections\`→\`connectionStats\`, \`settings\`/\`config\`→\`showSettings\`, \`alerts\`/\`thresholds\`→\`alertThresholdSet\`

**Top-Level Aliases**: \`pg.databaseSize()\`, \`pg.tableSizes()\`, \`pg.connectionStats()\`, \`pg.serverVersion()\`, \`pg.uptime()\`, \`pg.showSettings()\`, \`pg.recoveryStatus()\`, \`pg.replicationStatus()\`, \`pg.capacityPlanning()\`, \`pg.resourceUsageAnalyze()\`, \`pg.alertThresholdSet()\``],
  ["partitioning", `# Partitioning Tools

- \`pg_create_partitioned_table\`: \`partitionBy\` case-insensitive. Supports \`schema.table\` format for \`name\` (auto-parsed). \`primaryKey\` accepts array (e.g., \`['id', 'event_date']\`). ⛔ \`primaryKey\`/\`unique\` must include partition key—throws validation error otherwise
- \`pg_create_partition\`: Use \`parent\`/\`table\`/\`parentTable\`. \`forValues\` is a raw SQL string: \`"FROM ('2024-01-01') TO ('2024-07-01')"\`, \`"IN ('US', 'CA')"\`, \`"WITH (MODULUS 4, REMAINDER 0)"\`. For DEFAULT partition, use \`isDefault: true\`. Supports \`schema.table\` format for \`parent\` (auto-parsed)
- \`pg_attach_partition\`/\`pg_detach_partition\`: Support \`schema.table\` format for \`parent\` and \`partition\` (auto-parsed). For DEFAULT partition, use \`isDefault: true\` or \`forValues: "DEFAULT"\`
- \`pg_list_partitions\`: Default \`limit: 50\` (use \`0\` for all). Returns \`{partitions, count, truncated, totalCount?}\`. Uses \`bounds\` field (consistent with \`pg_partition_info\`)
- \`pg_partition_info\`: Returns \`{tableInfo, partitions, totalSizeBytes}\`. Uses \`bounds\` field
- Both list/info tools support \`schema.table\` format (auto-parsed) and accept \`table\`, \`parent\`, \`parentTable\`, or \`name\` aliases
- Response structures: \`pg_create_partitioned_table\` → \`{success, table, partitionBy, partitionKey, primaryKey?}\`. \`pg_create_partition\` → \`{success, partition, parent, bounds, subpartitionBy?, subpartitionKey?}\`. \`pg_attach_partition\` → \`{success, parent, partition, bounds}\`. \`pg_detach_partition\` → \`{success, parent, partition}\`
- ⚠️ Sub-partitioning: \`subpartitionBy\`/\`subpartitionKey\` on \`pg_create_partition\` makes a partition itself partitionable. The parent's \`primaryKey\` must include the sub-partition key column (PostgreSQL constraint)
- 📍 Code Mode: \`pg.partitioning.create()\` = \`createPartition\`, NOT \`createPartitionedTable\``],
  ["partman", `# pg_partman Tools

- \`pg_partman_create_parent\`: Interval uses PostgreSQL syntax ('1 day', '1 month') NOT keywords ('daily'). \`startPartition\` accepts 'now' shorthand for current date. Required params: \`parentTable\`/\`table\`, \`controlColumn\`/\`control\`/\`column\`, \`interval\`
- \`pg_partman_run_maintenance\`: Without \`parentTable\`, maintains ALL partition sets. Returns \`partial: true\` when some tables are skipped. \`orphaned\` object groups orphaned configs with \`count\`, \`tables\`, and cleanup \`hint\`. \`errors\` array for other failures
- \`pg_partman_show_config\`: Default \`limit: 50\` (use \`0\` for all). Returns \`truncated\` + \`totalCount\` when limited. \`orphaned\` flag per config. Supports \`schema.table\` or plain table name (auto-prefixes \`public.\`)
- \`pg_partman_show_partitions\`: Default \`limit: 50\` (use \`0\` for all). Returns \`truncated\` + \`totalCount\` when limited. \`parentTable\` required. Supports \`schema.table\` format (auto-parsed)
- \`pg_partman_check_default\`/\`partition_data\`: \`parentTable\` required. Supports \`schema.table\` format (auto-parsed)
- \`pg_partman_set_retention\`: ⚠️ **CAUTION: Default is DROP** — \`retentionKeepTable: false\` (default) = DROP partitions, \`true\` = detach only (safer). Pass \`retention: null\` to disable retention
- \`pg_partman_undo_partition\`: \`targetTable\` MUST exist before calling. Requires both \`parentTable\` and \`targetTable\`/\`target\`. ⚠️ Parent table and child partitions remain after undo—use \`DROP TABLE parent CASCADE\` to clean up
- \`pg_partman_analyze_partition_health\`: Default \`limit: 50\` (use \`0\` for all). Returns \`truncated\` + \`totalCount\` when limited. \`summary.overallHealth\`: 'healthy'|'warnings'|'issues_found'
- 📝 **Schema Resolution**: All partman tools auto-prefix \`public.\` when no schema specified in \`parentTable\`
- 📝 **Aliases**: \`parentTable\` accepts \`table\`, \`parent\`, \`name\`. \`controlColumn\` accepts \`control\`, \`column\`. \`targetTable\` accepts \`target\`
- 📝 **Strict Error Handling**: Attempting to query unmanaged tables (e.g. via \`pg_partman_show_config\`) throws \`TABLE_NOT_FOUND\`. Missing the extension completely throws \`EXTENSION_MISSING\` — remediate via \`pg_partman_create_extension\` before using partman tools.`],
  ["performance", `# Performance Tools

Core (24 methods): \`explain()\`, \`explainAnalyze()\`, \`explainBuffers()\`, \`indexStats()\`, \`tableStats()\`, \`statStatements()\`, \`statActivity()\`, \`locks()\`, \`bloatCheck()\`, \`cacheHitRatio()\`, \`seqScanTables()\`, \`indexRecommendations()\`, \`queryPlanCompare()\`, \`baseline()\`, \`connectionPoolOptimize()\`, \`partitionStrategySuggest()\`, \`unusedIndexes()\`, \`duplicateIndexes()\`, \`vacuumStats()\`, \`queryPlanStats()\`, \`diagnoseDatabasePerformance()\`, \`detectQueryAnomalies()\`, \`detectBloatRisk()\`, \`detectConnectionSpike()\`

Wrappers (3): \`blockingQueries()\`→\`locks({showBlocked:true})\`, \`longRunningQueries({ seconds | minDuration }?)\` filters by duration (returns \`{longRunningQueries, count, threshold}\`), \`analyzeTable({ table })\` runs ANALYZE (accepts \`schema.table\` format)

- \`explain({ sql, format?, params? })\`: Supports \`format: 'text'|'json'|'yaml'|'xml'\`. Default: text. Use \`params: [value]\` for \`$1, $2\` placeholders
- \`explainAnalyze({ sql, format?, params? })\`: Same format/params options as explain
- \`explainBuffers({ sql, params? })\`: Always returns JSON format (includes buffer statistics)
- \`indexRecommendations({ sql?, params? })\`: Pass \`params: [value]\` for parameterized queries (e.g., \`sql: 'SELECT * FROM orders WHERE id = $1', params: [5]\`)
- \`queryPlanCompare({ query1, query2, params1?, params2?, compact? })\`: Compare two query plans. Accepts \`sql1\`/\`sql2\` or \`sqlA\`/\`sqlB\` as aliases for \`query1\`/\`query2\`. Use \`compact: true\` to fetch analysis metrics only, omitting large JSON execution plans.
- \`partitionStrategySuggest({ table })\`: Accepts \`schema.table\` format (auto-parsed) or separate \`table\` + \`schema\` params
- ⚠️ **Data Type Awareness**: Query literals must match column types exactly—\`WHERE sensor_id = 1\` (integer), not \`'sensor_1'\` (string)

Aliases: \`cacheStats\`→\`cacheHitRatio\`, \`queryStats\`→\`statStatements\`, \`activity\`→\`statActivity\`, \`vacuum\`→\`vacuumStats\`, \`indexUsage\`→\`indexStats\`, \`bloatEstimate\`/\`bloat\`→\`bloatCheck\`, \`runningQueries\`→\`longRunningQueries\`

📦 **AI-Optimized Payloads**: Tools return limited results by default to reduce context size:

- \`indexStats({ limit? })\`: Default 50 rows. Returns \`truncated: true\` + \`totalCount\` when limited. Use \`limit: 0\` for all
- \`tableStats({ limit? })\`: Default 50 rows. Returns \`truncated: true\` + \`totalCount\` when limited. Use \`limit: 0\` for all
- \`vacuumStats({ limit? })\`: Default 50 rows. Same truncation indicators. Use \`limit: 0\` for all
- \`statStatements({ limit?, orderBy? })\`: Default 20 rows, **max 500**. Returns \`truncated: true\` + \`totalCount\` when limited. \`limit: 0\` returns up to the 500-row cap
- \`unusedIndexes({ limit?, summary? })\`: Default 20 rows. Use \`summary: true\` for aggregated stats by schema
- \`queryPlanStats({ limit?, truncateQuery? })\`: Default 20 rows, **max 500**, queries truncated to 100 chars. Use \`truncateQuery: 0\` for full text
- \`seqScanTables({ minScans?, schema?, limit? })\`: Default \`minScans: 10\`, \`limit: 50\`. Use \`minScans: 0\` for all tables; \`limit: 0\` for unlimited. Returns \`truncated: true\` + \`totalCount\` when limited
- \`locks({ showBlocked?, limit? })\`: Default 100 rows. Returns \`count\` + \`truncated\`. Use \`limit: 0\` for all. \`showBlocked: true\` returns blocking/blocked query pairs instead of the full lock list
- \`statActivity({ includeIdle?, limit?, truncateQuery? })\`: Default 100 connections (excludes idle), queries truncated to 100 chars. Returns \`count\`, \`truncated\`, and \`backgroundWorkers\`. Use \`limit: 0\` for all; \`includeIdle: true\` to include idle connections
- \`detectQueryAnomalies({ threshold?, minCalls? })\`: \`threshold\` must be 0.5–10 (default 2.0); \`minCalls\` must be 1–10000 (default 10). Out-of-range values return a structured validation error
- \`detectBloatRisk({ minRows?, schema? })\`: \`minRows\` must be 0–1,000,000 (default 1000). Nonexistent \`schema\` returns a P154 existence error
- \`detectConnectionSpike({ warningPercent? })\`: Default 70. Flags users/apps holding ≥ \`warningPercent\`% of connections. Value is clamped to 10–100 (not \`threshold\` — that key is ignored)

📍 **Code Mode Note**: \`pg_performance_baseline\` → \`pg.performance.baseline({ name? })\` (not \`performanceBaseline\`). Optional \`name\` param labels the snapshot; defaults to an ISO timestamp. \`indexRecommendations\` accepts \`query\` alias for \`sql\`

⚠️ **Extension Dependency**: \`diagnoseDatabasePerformance\` uses \`pg_stat_activity\` (not \`pg_stat_statements\`) for slow query detection — it runs correctly even when \`pg_stat_statements\` is unavailable. \`statStatements\` and \`queryPlanStats\` require the \`pg_stat_statements\` extension and return a structured \`QUERY_ERROR\` if it is not installed.

**Top-Level Aliases**: \`pg.explain()\`, \`pg.explainAnalyze()\`, \`pg.cacheHitRatio()\`, \`pg.indexStats()\`, \`pg.tableStats()\`, \`pg.indexRecommendations()\`, \`pg.bloatCheck()\`, \`pg.vacuumStats()\`, \`pg.unusedIndexes()\`, \`pg.duplicateIndexes()\`, \`pg.seqScanTables()\`, \`pg.diagnoseDatabasePerformance()\`, \`pg.detectQueryAnomalies()\`, \`pg.detectBloatRisk()\`, \`pg.detectConnectionSpike()\``],
  ["pgcrypto", `# pgcrypto Tools

Core: \`createExtension()\`, \`hash()\`, \`hmac()\`, \`encrypt()\`, \`decrypt()\`, \`genRandomUuid()\`, \`genRandomBytes()\`, \`genSalt()\`, \`crypt()\`

- \`pg_pgcrypto_create_extension\`: Enable pgcrypto extension (idempotent). Returns \`{success, message}\`
- \`pg_pgcrypto_hash\`: Hash data using digest algorithms. \`algorithm\`: 'md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512'. \`encoding\`: 'hex' (default), 'base64'. Returns \`{hash, algorithm, encoding, inputLength}\`
- \`pg_pgcrypto_hmac\`: HMAC authentication. Same algorithms as hash. Returns \`{hmac, algorithm, encoding}\`. \`key\` param for secret
- \`pg_pgcrypto_encrypt\`: PGP symmetric encryption. \`data\` + \`password\`/\`key\` (aliases). Optional \`options\` for cipher config (e.g., 'cipher-algo=aes256'). Returns \`{encrypted, encoding: 'base64'}\`
- \`pg_pgcrypto_decrypt\`: Decrypt PGP-encrypted data. \`data\`/\`encryptedData\` + \`password\`/\`key\` (aliases). Returns \`{decrypted, verified}\`. ⛔ Throws on wrong key/corrupt data
- \`pg_pgcrypto_gen_random_uuid\`: Generate UUID v4. Optional \`count\` (1-100, default 1). Returns \`{uuid, uuids, count}\` (\`uuid\` convenience property for single requests)
- \`pg_pgcrypto_gen_random_bytes\`: Generate random bytes. \`length\` (1-1024). \`encoding\`: 'hex' (default), 'base64'. Returns \`{randomBytes, length, encoding}\`
- \`pg_pgcrypto_gen_salt\`: Generate salt for crypt(). \`type\`: 'bf' (bcrypt, recommended), 'md5', 'xdes', 'des'. Optional \`iterations\` for bf (4-31) or xdes. Returns \`{salt, type}\`
- \`pg_pgcrypto_crypt\`: Hash password with salt. Use stored hash as salt for verification. Returns \`{hash, algorithm}\`. Verification: \`crypt(password, storedHash).hash === storedHash\`

**Password Workflow**: 1) \`genSalt({type:'bf', iterations:10})\` → 2) \`crypt({password, salt})\` → store hash → 3) Verify: \`crypt({password, salt: storedHash})\` and compare hashes

**Top-Level Aliases**: \`pg.pgcryptoHash()\`, \`pg.pgcryptoEncrypt()\`, \`pg.pgcryptoDecrypt()\`, \`pg.pgcryptoGenRandomUuid()\`, etc.

**Discovery**: \`pg.pgcrypto.help()\` returns \`{methods, methodAliases, examples}\` object`],
  ["postgis", `# PostGIS Tools

**Geometry Creation:**

- \`pg_geocode\`: Create point geometry from lat/lng. Returns \`{geojson, wkt}\`. ⚠️ Validates bounds: lat ±90°, lng ±180°
- \`pg_geometry_column\`: Add geometry column to table. \`ifNotExists\` returns \`{alreadyExists: true}\`
- \`pg_spatial_index\`: Create GiST spatial index. Auto-generates name if not provided. \`ifNotExists\` supported

**Spatial Queries:**

- \`pg_distance\`: Find geometries within distance from point. Returns \`{results, count}\` with \`distance_meters\`. ⚠️ Validates point bounds
- \`pg_bounding_box\`: Find geometries within lat/lng bounding box. Use \`select\` array for specific columns
- \`pg_intersection\`: Find geometries intersecting a WKT/GeoJSON geometry. Auto-detects SRID from column
- \`pg_point_in_polygon\`: Check if point is within table polygons. Returns \`{containingPolygons, count}\`. ⚠️ Validates point bounds. Returns \`warning\` field if column contains non-POLYGON geometry (e.g., POINT)

**Geometry Operations (Table-based):**

- \`pg_buffer\`: Create buffer zone around table geometries. Default limit: 10 rows. Default simplify: 10m (set \`simplify: 0\` to disable). Returns \`truncated: true\` + \`totalCount\` when results are truncated. Use \`limit: 0\` for all rows
- \`pg_geo_transform\`: Transform table geometries between SRIDs. Default limit: 10 rows. Returns \`truncated: true\` + \`totalCount\` when results are truncated. Use \`limit: 0\` for all rows. Auto-detects \`fromSrid\` from column metadata if not provided (returns \`autoDetectedSrid: true\`). \`fromSrid\`/\`sourceSrid\` and \`toSrid\`/\`targetSrid\` aliases
- \`pg_geo_cluster\`: Spatial clustering (DBSCAN/K-Means). K-Means: If \`numClusters\` exceeds row count, automatically clamps to available rows with \`warning\` field. DBSCAN: Returns contextual \`hints\` array explaining parameter effects (e.g., "All points formed single cluster—decrease eps") and \`parameterGuide\` explaining eps/minPoints trade-offs

**Geometry Operations (Standalone WKT/GeoJSON):**

- \`pg_geometry_buffer\`: Create buffer around WKT/GeoJSON. Returns \`{buffer_geojson, buffer_wkt, distance_meters}\`. Optional \`simplify\` param (meters) reduces polygon complexity—returns \`simplified\`, \`simplifyTolerance\` when applied. ⚠️ Returns \`warning\` if simplify tolerance is too high and geometry collapses to null
- \`pg_geometry_transform\`: Transform WKT/GeoJSON between SRIDs. Returns \`{transformed_geojson, transformed_wkt, fromSrid, toSrid}\`
- \`pg_geometry_intersection\`: Compute intersection of two geometries. Returns \`{intersects, intersection_geojson, intersection_area_sqm}\`. Normalizes SRID (4326) automatically—safe to mix GeoJSON and WKT

**Administration:**

- \`pg_postgis_create_extension\`: Enable PostGIS extension (idempotent). Returns \`{alreadyExists: true}\` when already installed
- \`pg_geo_index_optimize\`: Analyze spatial indexes. Without \`table\` param, analyzes all spatial indexes. Returns structured error (\`TABLE_NOT_FOUND\`) if specified table has no spatial columns or indexes

**Code Mode Aliases:** \`pg.postgis.addColumn()\` → \`geometryColumn\`, \`pg.postgis.indexOptimize()\` → \`geoIndexOptimize\`, \`pg.postgis.geoCluster()\` → \`pg_geo_cluster\`, \`pg.postgis.geoTransform()\` → \`pg_geo_transform\`. Note: \`pg.{group}.help()\` returns \`{methods, methodAliases, examples}\``],
  ["schema", `# Schema Tools

Core: \`listSchemas()\`, \`createSchema()\`, \`dropSchema()\`, \`listViews()\`, \`createView()\`, \`dropView()\`, \`listSequences()\`, \`createSequence()\`, \`dropSequence()\`, \`listFunctions()\`, \`listTriggers()\`, \`listConstraints()\`

Response Structures:

- \`listSchemas()\`: \`{schemas: string[], count}\`
- \`listViews({ includeMaterialized?, truncateDefinition?, limit?, schema? })\`: \`{views: [{schema, name, type, definition, definitionTruncated?}], count, hasMatViews, truncatedDefinitions?, truncated, totalCount?, note?}\`. Default \`limit: 50\` (use \`0\` for all). Default \`truncateDefinition: 500\` chars (use \`0\` for full definitions). \`truncated\` always included (\`true\`/\`false\`). \`totalCount\` included when truncated. ⚠️ Validates schema existence—nonexistent schema returns \`{success: false, error: "..."}\`
- \`listSequences({ schema?, limit? })\`: \`{sequences: [{schema, name, owned_by}], count, truncated, totalCount?, note?}\`. Default \`limit: 50\` (use \`0\` for all). Returns \`truncated: true\` + \`totalCount\` when results are limited. ⚠️ Validates schema existence—nonexistent schema returns \`{success: false, error: "..."}\`. Note: \`owned_by\` omits \`public.\` prefix for sequences in public schema (e.g., \`users.id\` not \`public.users.id\`)
- \`listFunctions({ schema?, limit?, exclude? })\`: \`{functions: [{schema, name, arguments, returns, language, volatility}], count, limit}\`
- \`listTriggers({ schema?, table? })\`: \`{triggers: [{schema, table_name, name, timing, events, function_name, enabled}], count}\`
- \`listConstraints({ schema?, table?, type? })\`: \`{constraints: [{schema, table_name, name, type, definition}], count}\`. Type filter values: \`primary_key\`, \`foreign_key\`, \`unique\`, \`check\`. Returned \`type\` field uses matching human-readable names
- \`dropSchema/dropView/dropSequence\`: All return \`{existed: true/false}\` to indicate if object existed before drop
- \`createSchema/createSequence\` (with \`ifNotExists\`) and \`createView\` (with \`orReplace\`): Return \`{alreadyExisted: true/false}\` when the flag is set. Without \`ifNotExists\`/\`orReplace\`, the field is omitted

- \`pg_create_view\`: Supports \`schema.name\` format (auto-parsed). Use \`orReplace: true\` for CREATE OR REPLACE. \`checkOption\`: 'cascaded', 'local', 'none'. ⛔ OR REPLACE can add new columns but cannot rename/remove existing ones—PostgreSQL limitation
- \`pg_create_sequence\`: Supports \`schema.name\` format. Parameters: \`start\`, \`increment\`, \`minValue\`, \`maxValue\`, \`cache\`, \`cycle\`, \`ownedBy\`, \`ifNotExists\`
- \`pg_list_functions\`: Default limit=500. Use \`schema: 'public'\`, \`limit: 2000\`, or \`exclude: ['postgis', 'pg_trgm', 'ltree', 'citext', 'fuzzystrmatch', 'pg_stat_statements', 'hypopg', 'unaccent', 'pg_stat_kcache', 'pgcrypto', 'partman', 'vector', 'topology']\` to filter. ⚠️ \`exclude\` filters by **schema name** AND extension-owned functions. The \`language\` filter does NOT exclude extension functions—use \`exclude\` alongside \`language\` for clean results. Note: Aggressive \`exclude\` may return 0 results if all functions belong to excluded extensions

📦 **AI-Optimized Payloads**: \`listViews({ limit? })\` and \`listSequences({ limit? })\` both default to 50 rows. Returns \`truncated: true\` + \`totalCount\` when limited. Use \`limit: 0\` for all

**Discovery**: \`pg.schema.help()\` returns \`{methods, methodAliases, examples}\` object`],
  ["stats", `# Stats Tools

- All stats tools support \`schema.table\` format (auto-parsed, embedded schema takes priority over explicit \`schema\` param)
- \`timeSeries\`: Both \`timeColumn\` (must be timestamp/date) and \`valueColumn\` (must be numeric) are validated upfront with clear error messages. Aliases: \`time\`→\`timeColumn\`, \`value\`→\`valueColumn\`. \`interval\` accepts: \`second\`, \`minute\`, \`hour\`, \`day\`, \`week\`, \`month\`, \`year\` (keywords, PostgreSQL format, or plurals). Default \`limit: 100\` time buckets. Use \`limit: 0\` for no limit. Returns \`truncated\` and \`totalCount\` indicators when default limit is applied. **groupBy payloads**: Default \`groupLimit: 20\` groups. Returns \`truncated\` + \`totalGroupCount\` when groups are limited. Use \`groupLimit: 0\` for all groups
- \`correlation\`: Use \`column1\`/\`column2\` or aliases \`x\`/\`y\` for column names
- \`distribution\`: Returns \`skewness\`, \`kurtosis\` (excess). \`buckets\` must be > 0. **groupBy payloads**: Default \`groupLimit: 20\` groups (prevents large payloads with many histogram buckets per group). Returns \`truncated\` + \`totalGroupCount\` when groups are limited. Use \`groupLimit: 0\` for all groups
- \`sampling\`: Defaults to \`random\` method with 20 rows (optimized for LLM context). \`sampleSize\` always takes precedence over \`percentage\`. ⚠️ \`percentage\` param only works with \`bernoulli\`/\`system\` methods—ignored for default \`random\` method. Default limit of 100 rows applied to \`bernoulli\`/\`system\` with \`percentage\` to prevent large payloads. Returns \`truncated\` and \`totalSampled\` when TABLESAMPLE returns more rows than limit
- \`percentiles\`: Accepts 0-1 or 0-100 (auto-normalized). ⚠️ Use consistent scale—mixing (e.g., \`[0.1, 50]\`) produces unexpected keys and returns a \`warning\` field explaining the issue. Empty array → defaults [0.25, 0.5, 0.75]
- \`hypothesis\`: Returns nested \`results\` object containing \`pValue\` (two-tailed), \`testStatistic\`, \`interpretation\`, \`sampleMean\`, \`sampleStdDev\`. Access via \`hyp.results.pValue\`. Use \`populationStdDev\` for z-test, otherwise defaults to t-test
- \`regression\`: Use \`xColumn\`/\`yColumn\`, aliases \`x\`/\`y\`, or \`column1\`/\`column2\` (for consistency with correlation). Returns nested \`regression\` object containing \`slope\`, \`intercept\`, \`rSquared\`, \`equation\`, \`avgX\`, \`avgY\`, \`sampleSize\`. Access via \`reg.regression.slope\`
- ⚠️ WARNING: \`sampling\` with \`system\` method unreliable for small tables—use \`bernoulli\` or \`random\`

**Window Functions (6 tools):**

- \`pg_stats_row_number({ table, orderBy, partitionBy?, selectColumns?, where?, limit? })\`: Sequential numbering within ordered result. \`partitionBy\` restarts numbering per group. Default \`limit: 100\`. Returns \`{success, rowCount, rows}\`
- \`pg_stats_rank({ table, orderBy, rankType?, partitionBy?, selectColumns?, where?, limit? })\`: Rank within ordered set. \`rankType\`: 'rank' (default, with gaps), 'dense_rank' (no gaps), 'percent_rank' (0-1). Default \`limit: 100\`. Returns \`{success, rankType, rowCount, rows}\`
- \`pg_stats_lag_lead({ table, column, orderBy, direction, offset?, defaultValue?, partitionBy?, selectColumns?, where?, limit? })\`: Access previous (\`lag\`) or next (\`lead\`) row values. \`direction\`: 'lag' or 'lead'. \`offset\` (default: 1) = number of rows to look back/ahead. \`defaultValue\` fills when no row exists. Default \`limit: 100\`. Returns \`{success, direction, offset, rowCount, rows}\`
- \`pg_stats_running_total({ table, column, orderBy, partitionBy?, selectColumns?, where?, limit? })\`: Cumulative running total using \`SUM OVER\`. \`partitionBy\` resets total per group. Default \`limit: 100\`. Returns \`{success, valueColumn, rowCount, rows}\`
- \`pg_stats_moving_avg({ table, column, orderBy, windowSize, partitionBy?, selectColumns?, where?, limit? })\`: Moving average over sliding window. \`windowSize\` = number of rows in window (default: 3). Default \`limit: 100\`. Returns \`{success, valueColumn, windowSize, rowCount, rows}\`
- \`pg_stats_ntile({ table, orderBy, buckets, partitionBy?, selectColumns?, where?, limit? })\`: Divide rows into N equal buckets. \`buckets\` = number of groups (e.g., 4 for quartiles). Default \`limit: 100\`. Returns \`{success, buckets, rowCount, rows}\`

**Outlier Detection:**

- \`pg_stats_outliers({ table, column, method?, threshold?, where?, limit?, maxOutliers? })\`: Detect outliers using IQR or Z-score. \`method\`: 'iqr' (default, robust for non-normal data) or 'zscore'. IQR \`threshold\` (default: 1.5, use 3 for extreme). Z-score \`threshold\` (default: 3). \`maxOutliers\` (default: 50). Validates column is numeric. Returns \`{success, method, stats, outlierCount, totalRows, outliers, truncated?, totalOutliers?}\`. IQR stats: \`{q1, q3, iqr, lowerBound, upperBound}\`. Z-score stats: \`{mean, stdDev, lowerBound, upperBound}\`

**Advanced Analysis (4 tools):**

- \`pg_stats_top_n({ table, column, n?, orderDirection?, selectColumns?, where? })\`: Top N rows ranked by column. \`n\` (default: 10). \`orderDirection\`: 'desc' (default) or 'asc'. Auto-excludes long-content columns (text, json, bytea) unless \`selectColumns\` specified—returns \`hint\` when columns excluded. Returns \`{success, column, direction, count, rows, hint?}\`
- \`pg_stats_distinct({ table, column, where?, limit? })\`: Distinct values with total cardinality. Default \`limit: 100\`. Returns \`{success, column, distinctCount, values}\`
- \`pg_stats_frequency({ table, column, where?, limit? })\`: Value frequency distribution ordered by frequency desc. Default \`limit: 20\`. Returns \`{success, column, distinctValues, distribution: [{value, frequency, percentage}]}\`
- \`pg_stats_summary({ table, columns?, where? })\`: Summary statistics for multiple numeric columns. Defaults to all numeric columns if \`columns\` omitted. Returns \`{success, table, summaries: [{column, count, avg, min, max, stddev}]}\`

**Top-Level Aliases**: \`pg.descriptive()\`, \`pg.percentiles()\`, \`pg.correlation()\`, \`pg.regression()\`, \`pg.timeSeries()\`, \`pg.distribution()\`, \`pg.hypothesis()\`, \`pg.sampling()\`, \`pg.statsRowNumber()\`, \`pg.statsRank()\`, \`pg.statsLagLead()\`, \`pg.statsRunningTotal()\`, \`pg.statsMovingAvg()\`, \`pg.statsNtile()\`, \`pg.statsOutliers()\`, \`pg.statsTopN()\`, \`pg.statsDistinct()\`, \`pg.statsFrequency()\`, \`pg.statsSummary()\``],
  ["text", `# Text Tools

- \`pg_text_search\`/\`pg_text_rank\`: Column must be \`text\` type—pre-built \`tsvector\` columns are **not** supported (wrap with \`to_tsvector()\` fails on tsvector input). Use \`pg_read_query\` with raw FTS SQL for tsvector columns
- \`pg_create_fts_index\`: Returns \`{success, index, config, skipped}\`. \`skipped: true\` = index already existed (IF NOT EXISTS). \`ifNotExists\` defaults to \`true\`

Defaults: \`threshold\`=0.3 (use 0.1-0.2 for partial), \`maxDistance\`=3 (use 5+ for longer strings)

- All text tools support \`schema.table\` format (auto-parsed, embedded schema takes priority over explicit \`schema\` param)
- \`pg_text_search\`: Supports both \`column\` (singular string) and \`columns\` (array). Either is valid—\`column\` auto-converts to array
- 📦 **AI-Optimized Payloads**: All row-returning text tools (\`pg_text_search\`, \`pg_text_rank\`, \`pg_text_headline\`, \`pg_trigram_similarity\`, \`pg_fuzzy_match\`, \`pg_regexp_match\`, \`pg_like_search\`) default to 100 results. Returns \`truncated: true\` + \`hint\` when capped. Use \`limit: 0\` for all rows
- \`pg_fuzzy_match\`: Levenshtein returns distance (lower=better). Soundex/metaphone return phonetic codes (exact match only). ⛔ Invalid \`method\` values throw error with valid options
- \`pg_text_normalize\`: Removes accents only (unaccent). Does NOT lowercase/trim
- 📍 **Table vs Standalone**: \`normalize\`, \`sentiment\`, \`toVector\`, \`toQuery\`, \`searchConfig\` are standalone (text input only). For phonetic matching: use \`pg_fuzzy_match\` with \`method: 'soundex'|'metaphone'\` (direct MCP), or \`pg.text.soundex()\`/\`pg.text.metaphone()\` (Code Mode convenience wrappers that call fuzzyMatch internally)

**Top-Level Aliases**: \`pg.textSearch()\`, \`pg.textRank()\`, \`pg.textHeadline()\`, \`pg.textNormalize()\`, \`pg.textSentiment()\`, \`pg.textToVector()\`, \`pg.textToQuery()\`, \`pg.textSearchConfig()\`, \`pg.textTrigramSimilarity()\`, \`pg.textFuzzyMatch()\`, \`pg.textLikeSearch()\`, \`pg.textRegexpMatch()\`, \`pg.textCreateFtsIndex()\``],
  ["transactions", `# Transactions

Core: \`begin()\`, \`status()\`, \`commit()\`, \`rollback()\`, \`savepoint()\`, \`rollbackTo()\`, \`release()\`, \`execute()\`

**Transaction Lifecycle:**

- \`pg_transaction_begin\`: Start new transaction. Supports optional \`isolationLevel\` and \`read_only\`/\`readOnly\` parameters. Returns \`{transactionId, isolationLevel, read_only, message}\`. Use \`transactionId\` for subsequent operations
- \`pg_transaction_status\`: Check transaction state without modifying it. Returns \`{status, transactionId, active, message}\`. \`status\` is \`"active"\` (ready), \`"aborted"\` (needs rollback), or \`"not_found"\` (already ended). Read-only — does not alter transaction state. \`transactionId\`/\`tx\`/\`txId\` aliases
- \`pg_transaction_commit\`: Commit transaction, making all changes permanent. \`transactionId\`/\`tx\`/\`txId\` aliases
- \`pg_transaction_rollback\`: Rollback transaction, discarding all changes. \`transactionId\`/\`tx\`/\`txId\` aliases

**Savepoints:**

- \`pg_transaction_savepoint\`: Create savepoint within transaction. \`name\`/\`savepoint\` + \`transactionId\`/\`tx\`/\`txId\`
- \`pg_transaction_rollback_to\`: Rollback to savepoint, restoring database state to when the savepoint was created. ⚠️ Undoes ALL work (data changes AND savepoints) created after the target savepoint
- \`pg_transaction_release\`: Release savepoint, keeping all changes since it was created. \`name\`/\`savepoint\` aliases

**Atomic Execution:**

- \`pg_transaction_execute\`: Execute multiple statements atomically. Two modes:
  - **Auto-commit**: Without \`transactionId\`—auto-commits on success, auto-rollbacks on any error
  - **Join existing**: With \`transactionId\`/\`tx\`/\`txId\`—no auto-commit, caller controls via commit/rollback
- \`statements\`: Array of \`{sql: "...", params?: [...]}\` objects. ⚠️ Each object MUST have \`sql\` key
- \`isolationLevel\`: Optional isolation level for new transactions ('READ COMMITTED', 'REPEATABLE READ', 'SERIALIZABLE')
- \`read_only\`/\`readOnly\`: Optional boolean. If true, protects against mutating writes natively using Postgres boundary constraints
- Supports SELECT statements inside \`statements\`—results include \`rows\` in the response for mixed read/write workflows

**Aborted Transaction State:**

- ⚠️ If any statement in a transaction fails, PostgreSQL puts the transaction into an **aborted state**
- In aborted state, only \`ROLLBACK\` or \`ROLLBACK TO SAVEPOINT\` commands are accepted—all other commands will error
- Use \`pg_transaction_rollback\` to end the transaction, or \`pg_transaction_rollback_to\` to recover to a savepoint
- \`pg_transaction_commit\` on an aborted transaction will detect the state and report it (not silently rollback)

**Response Structures:**

- \`begin\`: \`{success, transactionId, isolationLevel: 'READ COMMITTED', read_only, message}\`
- \`status\`: \`{success, status: 'active'|'aborted'|'not_found', transactionId, active, message}\`
- \`commit/rollback\`: \`{success, transactionId, message}\`
- \`savepoint/release/rollbackTo\`: \`{success, transactionId, savepoint, message}\`
- \`execute\`: \`{success, statementsExecuted, results: [{sql, rowsAffected, rowCount, rows?}], transactionId?, autoRolledBack?}\`

**Discovery**: \`pg.transactions.help()\` returns \`{methods, methodAliases, examples}\``],
  ["vector", `# Vector Tools

⚠️ **Large Vectors**: Direct MCP tool calls may truncate vectors >256 dimensions due to JSON-RPC message size limits. For vectors ≥256 dimensions (e.g., OpenAI 1536-dim, local 384-dim), use Code Mode: \`await pg.vector.search({table, column, vector, limit})\`

- \`pg_vector_search\`: Supports \`schema.table\` format (auto-parsed). Returns \`{success, results: [...], count, metric}\`. Use \`select: ["id", "name"]\` to include identifying columns. Without select, only returns distance. \`filter\` = \`where\`. ⚠️ Vectors read from DB are strings—parse before passing: \`vec.replace(/^\\[|\\]$/g, '').split(',').map(Number)\`
- \`pg_vector_insert\`: Supports \`schema.table\` format (auto-parsed). Use \`updateExisting\` + \`conflictColumn\` + \`conflictValue\` for UPDATE mode. \`additionalColumns\` is applied in both INSERT and UPDATE modes
- \`pg_vector_batch_insert\`: \`vectors\` expects \`[{vector: [...], data?: {...}}]\` objects, not raw arrays
- \`pg_vector_normalize\`: Returns \`{success, normalized: [...], magnitude: N}\`. Note: \`magnitude\` is the **original** vector length (not 1)
- \`pg_vector_aggregate\`: Supports \`schema.table\` format (auto-parsed). ⛔ Validates column is vector type. Returns \`{success, average_vector: {preview, dimensions, truncated}, count}\` or \`{success, groups: [{group_key, average_vector, count}]}\` with groupBy. ⚠️ \`groupBy\` only supports simple column names (not expressions)
- \`pg_vector_dimension_reduce\`: Direct mode returns \`{success, reduced: [...], originalDimensions, targetDimensions}\`. Table mode returns \`{success, rows: [{id, original_dimensions, reduced}], processedCount, summarized}\`. Default \`summarize: true\` in table mode returns compact \`{preview, dimensions, truncated}\` format. Use \`summarize: false\` for full vectors
- \`pg_vector_distance\`: Calculate distance between two vectors. \`metric\`: 'l2' (default), 'cosine', 'inner_product'. Returns \`{success, distance, metric}\`
- \`pg_vector_cluster\`: \`clusters\` = \`k\`. Returns centroids with \`{preview, dimensions, truncated}\` format for large vectors (>10 dims)—use \`pg_vector_distance\` to assign rows
- \`pg_vector_create_index\`: Use \`type\` (or alias \`method\`) with values 'ivfflat' or 'hnsw'. IVFFlat: \`lists\` param. HNSW: \`m\`, \`efConstruction\` params. Supports explicit index naming via \`indexName\` (alias \`name\`). Includes strict idempotency support with \`ifNotExists: true\`.
- \`pg_vector_performance\`: Auto-generates testVector from first row if omitted. Returns \`testVectorSource: 'auto-generated from first row'|'user-provided'\`
- \`pg_vector_validate\`: Returns \`{valid: bool, vectorDimensions}\`. Empty vector \`[]\` returns \`{valid: true, vectorDimensions: 0}\`
- ⛔ \`pg_vector_embed\`: Demo only (hash-based). Use OpenAI/Cohere for production.
- \`pg_hybrid_search\`: Supports \`schema.table\` format (auto-parsed). Combines vector similarity and full-text search with weighted scoring. ⚠️ Text query param is \`textQuery\` (alias: \`queryText\`) — **not** \`query\`. \`textColumn\` auto-detects type: uses tsvector columns directly, wraps text columns with \`to_tsvector()\`. Code mode alias: \`pg.hybridSearch()\` → \`pg.vector.hybridSearch()\`
- 📝 **Error Handling & Validation**: Vector tools return structured validation errors (\`{success: false, error: "..."}\`) for dimension mismatches. Zod validation has been strictly enforced to eliminate internal framework refine leaks (no \`_truncated\` exposure in outputs). Token clamping on vector size uses strict payload \`limit\` parameters.`],
]);
