/**
 * postgres-mcp - Schema Re-exports: Extensions & Domain Types
 *
 * JSONB, text, vector, PostGIS, cron, partman, partitioning,
 * and extension (kcache, citext, ltree, pgcrypto) schemas.
 */

// JSONB operation schemas
export {
  // Base schemas for MCP visibility (Split Schema pattern)
  JsonbExtractSchemaBase,
  JsonbSetSchemaBase,
  JsonbContainsSchemaBase,
  JsonbPathQuerySchemaBase,
  JsonbInsertSchemaBase,
  JsonbDeleteSchemaBase,
  JsonbTypeofSchemaBase,
  JsonbKeysSchemaBase,
  JsonbStripNullsSchemaBase,
  JsonbAggSchemaBase,
  JsonbNormalizeSchemaBase,
  JsonbStatsSchemaBase,
  JsonbIndexSuggestSchemaBase,
  JsonbSecurityScanSchemaBase,
  // Full schemas (with preprocess - for handler parsing)
  JsonbExtractSchema,
  JsonbSetSchema,
  JsonbContainsSchema,
  JsonbPathQuerySchema,
  JsonbInsertSchema,
  JsonbDeleteSchema,
  JsonbTypeofSchema,
  JsonbKeysSchema,
  JsonbStripNullsSchema,
  JsonbAggSchema,
  JsonbNormalizeSchema,
  JsonbStatsSchema,
  JsonbIndexSuggestSchema,
  JsonbSecurityScanSchema,
  // Preprocess function for handlers
  preprocessJsonbParams,
  // Path normalization functions (for handler use)
  normalizePathToArray,
  normalizePathForInsert,
  normalizePathToString,
  parseJsonbValue,
  stringPathToArray,
  arrayPathToString,
  // JSONB output schemas
  JsonbExtractOutputSchema,
  JsonbSetOutputSchema,
  JsonbInsertOutputSchema,
  JsonbDeleteOutputSchema,
  JsonbContainsOutputSchema,
  JsonbPathQueryOutputSchema,
  JsonbAggOutputSchema,
  JsonbObjectOutputSchema,
  JsonbArrayOutputSchema,
  JsonbKeysOutputSchema,
  JsonbStripNullsOutputSchema,
  JsonbTypeofOutputSchema,
  JsonbValidatePathOutputSchema,
  JsonbMergeOutputSchema,
  JsonbNormalizeOutputSchema,
  JsonbDiffOutputSchema,
  JsonbIndexSuggestOutputSchema,
  JsonbSecurityScanOutputSchema,
  JsonbStatsOutputSchema,
} from "./jsonb/index.js";

// Text search schemas
export {
  TextSearchSchema,
  TextSearchSchemaBase,
  TrigramSimilaritySchema,
  TrigramSimilaritySchemaBase,
  RegexpMatchSchema,
  RegexpMatchSchemaBase,
  preprocessTextParams,
  // Text output schemas
  TextRowsOutputSchema,
  FtsIndexOutputSchema,
  TextNormalizeOutputSchema,
  TextSentimentOutputSchema,
  TextToVectorOutputSchema,
  TextToQueryOutputSchema,
  TextSearchConfigOutputSchema,
} from "./text-search.js";

// pgvector schemas
export {
  // Base schemas for MCP visibility (Split Schema pattern)
  VectorSearchSchemaBase,
  VectorCreateIndexSchemaBase,
  // Transformed schemas for handler validation
  VectorSearchSchema,
  VectorCreateIndexSchema,
  // Utilities
  FiniteNumberArray,
  // Output schemas
  VectorCreateExtensionOutputSchema,
  VectorAddColumnOutputSchema,
  VectorInsertOutputSchema,
  VectorSearchOutputSchema,
  VectorCreateIndexOutputSchema,
  VectorDistanceOutputSchema,
  VectorNormalizeOutputSchema,
  VectorAggregateOutputSchema,
  VectorClusterOutputSchema,
  VectorIndexOptimizeOutputSchema,
  HybridSearchOutputSchema,
  VectorPerformanceOutputSchema,
  VectorDimensionReduceOutputSchema,
  VectorEmbedOutputSchema,
  VectorValidateOutputSchema,
  VectorBatchInsertOutputSchema,
} from "./vector/index.js";

// PostGIS schemas
export {
  // Base schemas for MCP visibility
  GeometryColumnSchemaBase,
  GeometryDistanceSchemaBase,
  PointInPolygonSchemaBase,
  SpatialIndexSchemaBase,
  BufferSchemaBase,
  IntersectionSchemaBase,
  BoundingBoxSchemaBase,
  GeocodeSchemaBase,
  GeoTransformSchemaBase,
  GeoIndexOptimizeSchemaBase,
  GeoClusterSchemaBase,
  GeometryBufferSchemaBase,
  GeometryIntersectionSchemaBase,
  GeometryTransformSchemaBase,
  // Transformed schemas for handler validation
  GeometryColumnSchema,
  GeometryDistanceSchema,
  PointInPolygonSchema,
  SpatialIndexSchema,
  BufferSchema,
  IntersectionSchema,
  BoundingBoxSchema,
  GeocodeSchema,
  GeoTransformSchema,
  GeoIndexOptimizeSchema,
  GeoClusterSchema,
  GeometryBufferSchema,
  GeometryIntersectionSchema,
  GeometryTransformSchema,
  // Utility functions
  preprocessPostgisParams,
  preprocessPoint,
  convertToMeters,
  // Output schemas
  PostgisCreateExtensionOutputSchema,
  GeometryColumnOutputSchema,
  PointInPolygonOutputSchema,
  DistanceOutputSchema,
  BufferOutputSchema,
  IntersectionOutputSchema,
  BoundingBoxOutputSchema,
  SpatialIndexOutputSchema,
  GeocodeOutputSchema,
  GeoTransformOutputSchema,
  GeoIndexOptimizeOutputSchema,
  GeoClusterOutputSchema,
  GeometryBufferOutputSchema,
  GeometryIntersectionOutputSchema,
  GeometryTransformOutputSchema,
} from "./postgis/index.js";

// Partitioning schemas
export {
  // Base schemas for MCP visibility
  CreatePartitionedTableSchemaBase,
  CreatePartitionSchemaBase,
  AttachPartitionSchemaBase,
  DetachPartitionSchemaBase,
  ListPartitionsSchemaBase,
  PartitionInfoSchemaBase,
  // Transformed schemas for handler validation
  CreatePartitionedTableSchema,
  CreatePartitionSchema,
  AttachPartitionSchema,
  DetachPartitionSchema,
  ListPartitionsSchema,
  PartitionInfoSchema,
  // Output schemas
  ListPartitionsOutputSchema,
  CreatePartitionedTableOutputSchema,
  CreatePartitionOutputSchema,
  AttachPartitionOutputSchema,
  DetachPartitionOutputSchema,
  PartitionInfoOutputSchema,
} from "./partitioning/index.js";

// pg_cron schemas
export {
  CronCreateExtensionSchema,
  CronCreateExtensionSchemaBase,
  CronScheduleSchema,
  CronScheduleSchemaBase,
  CronScheduleInDatabaseSchema,
  CronScheduleInDatabaseSchemaBase,
  CronUnscheduleSchemaBase,
  CronUnscheduleSchema,
  CronAlterJobSchemaBase,
  CronAlterJobSchema,
  CronJobRunDetailsSchemaBase,
  CronJobRunDetailsSchema,
  CronListJobsSchemaBase,
  CronListJobsSchema,
  CronCleanupHistorySchema,
  CronCleanupHistorySchemaBase,
  // Output schemas
  CronCreateExtensionOutputSchema,
  CronScheduleOutputSchema,
  CronScheduleInDatabaseOutputSchema,
  CronUnscheduleOutputSchema,
  CronAlterJobOutputSchema,
  CronListJobsOutputSchema,
  CronJobRunDetailsOutputSchema,
  CronCleanupHistoryOutputSchema,
} from "./cron.js";

// pg_partman schemas
export {
  PartmanCreateParentSchema,
  PartmanCreateParentSchemaBase,
  DEPRECATED_INTERVALS,
  PartmanRunMaintenanceSchema,
  PartmanRunMaintenanceSchemaBase,
  PartmanShowPartitionsSchema,
  PartmanShowPartitionsSchemaBase,
  PartmanShowConfigSchema,
  PartmanShowConfigSchemaBase,
  PartmanCheckDefaultSchema,
  PartmanCheckDefaultSchemaBase,
  PartmanPartitionDataSchema,
  PartmanPartitionDataSchemaBase,
  PartmanRetentionSchema,
  PartmanRetentionSchemaBase,
  PartmanUndoPartitionSchema,
  PartmanUndoPartitionSchemaBase,
  PartmanUpdateConfigSchema,
  // Output schemas
  PartmanCreateExtensionOutputSchema,
  PartmanCreateParentOutputSchema,
  PartmanRunMaintenanceOutputSchema,
  PartmanShowPartitionsOutputSchema,
  PartmanShowConfigOutputSchema,
  PartmanCheckDefaultOutputSchema,
  PartmanPartitionDataOutputSchema,
  PartmanSetRetentionOutputSchema,
  PartmanUndoPartitionOutputSchema,
  PartmanAnalyzeHealthOutputSchema,
} from "./partman/index.js";

// Extension schemas (kcache, citext, ltree, pgcrypto)
export {
  // pg_stat_kcache
  KcacheQueryStatsSchemaBase,
  KcacheQueryStatsSchema,
  KcacheTopCpuSchemaBase,
  KcacheTopIoSchemaBase,
  KcacheDatabaseStatsSchemaBase,
  KcacheDatabaseStatsSchema,
  KcacheResourceAnalysisSchemaBase,
  KcacheResourceAnalysisSchema,
  // Kcache output schemas
  KcacheCreateExtensionOutputSchema,
  KcacheQueryStatsOutputSchema,
  KcacheTopCpuOutputSchema,
  KcacheTopIoOutputSchema,
  KcacheDatabaseStatsOutputSchema,
  KcacheResourceAnalysisOutputSchema,
  KcacheResetOutputSchema,
  // citext
  CitextCompareSchemaBase,
  CitextCompareSchema,
  CitextConvertColumnSchema,
  CitextConvertColumnSchemaBase,
  CitextListColumnsSchemaBase,
  CitextListColumnsSchema,
  CitextAnalyzeCandidatesSchema,
  CitextAnalyzeCandidatesSchemaBase,
  CitextSchemaAdvisorSchema,
  CitextSchemaAdvisorSchemaBase,
  // Citext output schemas
  CitextCreateExtensionOutputSchema,
  CitextConvertColumnOutputSchema,
  CitextListColumnsOutputSchema,
  CitextAnalyzeCandidatesOutputSchema,
  CitextCompareOutputSchema,
  CitextSchemaAdvisorOutputSchema,
  // ltree
  LtreeQuerySchema,
  LtreeQuerySchemaBase,
  LtreeSubpathSchema,
  LtreeSubpathSchemaBase,
  LtreeLcaSchemaBase,
  LtreeLcaSchema,
  LtreeMatchSchema,
  LtreeMatchSchemaBase,
  LtreeListColumnsSchemaBase,
  LtreeListColumnsSchema,
  LtreeConvertColumnSchema,
  LtreeConvertColumnSchemaBase,
  LtreeIndexSchema,
  LtreeIndexSchemaBase,
  // Ltree output schemas
  LtreeCreateExtensionOutputSchema,
  LtreeQueryOutputSchema,
  LtreeSubpathOutputSchema,
  LtreeLcaOutputSchema,
  LtreeMatchOutputSchema,
  LtreeListColumnsOutputSchema,
  LtreeConvertColumnOutputSchema,
  LtreeCreateIndexOutputSchema,
  // pgcrypto — Base schemas for MCP visibility (Split Schema pattern)
  PgcryptoCreateExtensionSchemaBase,
  PgcryptoGenRandomUuidSchemaBase,
  PgcryptoHashSchemaBase,
  PgcryptoHmacSchemaBase,
  PgcryptoRandomBytesSchemaBase,
  PgcryptoGenSaltSchemaBase,
  // pgcrypto — Full schemas for handler validation
  PgcryptoCreateExtensionSchema,
  PgcryptoGenRandomUuidSchema,
  PgcryptoHashSchema,
  PgcryptoHmacSchema,
  PgcryptoEncryptSchema,
  PgcryptoEncryptSchemaBase,
  PgcryptoDecryptSchema,
  PgcryptoDecryptSchemaBase,
  PgcryptoRandomBytesSchema,
  PgcryptoGenSaltSchema,
  PgcryptoCryptSchemaBase,
  PgcryptoCryptSchema,
  // Pgcrypto output schemas
  PgcryptoCreateExtensionOutputSchema,
  PgcryptoHashOutputSchema,
  PgcryptoHmacOutputSchema,
  PgcryptoEncryptOutputSchema,
  PgcryptoDecryptOutputSchema,
  PgcryptoGenRandomUuidOutputSchema,
  PgcryptoGenRandomBytesOutputSchema,
  PgcryptoGenSaltOutputSchema,
  PgcryptoCryptOutputSchema,
} from "./extensions/index.js";
