/**
 * postgres-mcp - Tool Constants
 *
 * Defines the tool groups and meta-groups used for filtering.
 *
 * TOOL COUNT NOTES:
 *   Counts and shortcut capacities are validated by unit tests in tool-filter.test.ts.
 *   The 248 "Specialized Tools" total encompasses all tools defined below,
 *   including Code Mode and extension utilities.
 *
 *   When adding new tools: update the group array below.
 *   Tests will catch inconsistencies automatically.
 */

import type { ToolGroup } from "../types/index.js";

/**
 * Default tool groups and their member tools.
 * This serves as the canonical mapping of tools to groups.
 */
export const TOOL_GROUPS: Record<ToolGroup, string[]> = {
  core: [
    "pg_read_query",
    "pg_write_query",
    "pg_list_tables",
    "pg_describe_table",
    "pg_create_table",
    "pg_drop_table",
    "pg_get_indexes",
    "pg_create_index",
    "pg_list_objects",
    "pg_object_details",
    "pg_list_extensions",
    "pg_analyze_db_health",
    "pg_analyze_workload_indexes",
    "pg_analyze_query_indexes",
    // Convenience tools
    "pg_upsert",
    "pg_batch_insert",
    "pg_count",
    "pg_exists",
    "pg_truncate",
    "pg_drop_index",
  ],
  transactions: [
    "pg_transaction_begin",
    "pg_transaction_commit",
    "pg_transaction_rollback",
    "pg_transaction_savepoint",
    "pg_transaction_release",
    "pg_transaction_rollback_to",
    "pg_transaction_execute",
    "pg_transaction_status",
  ],
  jsonb: [
    "pg_jsonb_extract",
    "pg_jsonb_set",
    "pg_jsonb_insert",
    "pg_jsonb_delete",
    "pg_jsonb_contains",
    "pg_jsonb_path_query",
    "pg_jsonb_agg",
    "pg_jsonb_object",
    "pg_jsonb_array",
    "pg_jsonb_keys",
    "pg_jsonb_strip_nulls",
    "pg_jsonb_typeof",
    "pg_jsonb_validate_path",
    "pg_jsonb_stats",
    "pg_jsonb_merge",
    "pg_jsonb_normalize",
    "pg_jsonb_diff",
    "pg_jsonb_index_suggest",
    "pg_jsonb_security_scan",
    "pg_jsonb_pretty",
  ],
  text: [
    "pg_text_search",
    "pg_text_rank",
    "pg_trigram_similarity",
    "pg_fuzzy_match",
    "pg_regexp_match",
    "pg_like_search",
    "pg_text_headline",
    "pg_create_fts_index",
    "pg_text_normalize",
    "pg_text_sentiment",
    "pg_text_to_vector",
    "pg_text_to_query",
    "pg_text_search_config",
  ],
  performance: [
    "pg_explain",
    "pg_explain_analyze",
    "pg_explain_buffers",
    "pg_index_stats",
    "pg_table_stats",
    "pg_stat_statements",
    "pg_stat_activity",
    "pg_locks",
    "pg_bloat_check",
    "pg_cache_hit_ratio",
    "pg_seq_scan_tables",
    "pg_index_recommendations",
    "pg_query_plan_compare",
    "pg_performance_baseline",
    "pg_connection_pool_optimize",
    "pg_partition_strategy_suggest",
    "pg_unused_indexes",
    "pg_duplicate_indexes",
    "pg_vacuum_stats",
    "pg_query_plan_stats",
    "pg_diagnose_database_performance",
    "pg_detect_query_anomalies",
    "pg_detect_bloat_risk",
    "pg_detect_connection_spike",
  ],
  admin: [
    "pg_vacuum",
    "pg_vacuum_analyze",
    "pg_analyze",
    "pg_reindex",
    "pg_terminate_backend",
    "pg_cancel_backend",
    "pg_reload_conf",
    "pg_set_config",
    "pg_reset_stats",
    "pg_cluster",
    "pg_append_insight",
  ],
  monitoring: [
    "pg_database_size",
    "pg_table_sizes",
    "pg_connection_stats",
    "pg_replication_status",
    "pg_server_version",
    "pg_show_settings",
    "pg_uptime",
    "pg_recovery_status",
    "pg_capacity_planning",
    "pg_resource_usage_analyze",
    "pg_alert_threshold_set",
  ],
  backup: [
    "pg_dump_table",
    "pg_dump_schema",
    "pg_copy_export",
    "pg_copy_import",
    "pg_create_backup_plan",
    "pg_restore_command",
    "pg_backup_physical",
    "pg_restore_validate",
    "pg_backup_schedule_optimize",
    "pg_audit_list_backups",
    "pg_audit_restore_backup",
    "pg_audit_diff_backup",
  ],
  schema: [
    "pg_list_schemas",
    "pg_create_schema",
    "pg_drop_schema",
    "pg_list_sequences",
    "pg_create_sequence",
    "pg_drop_sequence",
    "pg_list_views",
    "pg_create_view",
    "pg_drop_view",
    "pg_list_functions",
    "pg_list_triggers",
    "pg_list_constraints",
  ],
  vector: [
    "pg_vector_create_extension",
    "pg_vector_add_column",
    "pg_vector_insert",
    "pg_vector_batch_insert",
    "pg_vector_search",
    "pg_vector_create_index",
    "pg_vector_distance",
    "pg_vector_normalize",
    "pg_vector_aggregate",
    "pg_vector_cluster",
    "pg_vector_index_optimize",
    "pg_hybrid_search",
    "pg_vector_performance",
    "pg_vector_dimension_reduce",
    "pg_vector_embed",
    "pg_vector_validate",
  ],
  postgis: [
    "pg_postgis_create_extension",
    "pg_geometry_column",
    "pg_point_in_polygon",
    "pg_distance",
    "pg_buffer",
    "pg_intersection",
    "pg_bounding_box",
    "pg_spatial_index",
    "pg_geocode",
    "pg_geo_transform",
    "pg_geo_index_optimize",
    "pg_geo_cluster",
    "pg_geometry_buffer",
    "pg_geometry_intersection",
    "pg_geometry_transform",
  ],
  partitioning: [
    "pg_list_partitions",
    "pg_create_partition",
    "pg_attach_partition",
    "pg_detach_partition",
    "pg_partition_info",
    "pg_create_partitioned_table",
  ],
  stats: [
    "pg_stats_descriptive",
    "pg_stats_percentiles",
    "pg_stats_correlation",
    "pg_stats_regression",
    "pg_stats_time_series",
    "pg_stats_distribution",
    "pg_stats_hypothesis",
    "pg_stats_sampling",
    "pg_stats_row_number",
    "pg_stats_rank",
    "pg_stats_lag_lead",
    "pg_stats_running_total",
    "pg_stats_moving_avg",
    "pg_stats_ntile",
    "pg_stats_outliers",
    "pg_stats_top_n",
    "pg_stats_distinct",
    "pg_stats_frequency",
    "pg_stats_summary",
  ],
  cron: [
    "pg_cron_create_extension",
    "pg_cron_schedule",
    "pg_cron_schedule_in_database",
    "pg_cron_unschedule",
    "pg_cron_alter_job",
    "pg_cron_list_jobs",
    "pg_cron_job_run_details",
    "pg_cron_cleanup_history",
  ],
  partman: [
    "pg_partman_create_extension",
    "pg_partman_create_parent",
    "pg_partman_run_maintenance",
    "pg_partman_show_partitions",
    "pg_partman_show_config",
    "pg_partman_check_default",
    "pg_partman_partition_data",
    "pg_partman_set_retention",
    "pg_partman_undo_partition",
    "pg_partman_analyze_partition_health",
  ],
  kcache: [
    "pg_kcache_create_extension",
    "pg_kcache_query_stats",
    "pg_kcache_top_cpu",
    "pg_kcache_top_io",
    "pg_kcache_database_stats",
    "pg_kcache_resource_analysis",
    "pg_kcache_reset",
  ],
  citext: [
    "pg_citext_create_extension",
    "pg_citext_convert_column",
    "pg_citext_list_columns",
    "pg_citext_analyze_candidates",
    "pg_citext_compare",
    "pg_citext_schema_advisor",
  ],
  ltree: [
    "pg_ltree_create_extension",
    "pg_ltree_query",
    "pg_ltree_subpath",
    "pg_ltree_lca",
    "pg_ltree_match",
    "pg_ltree_list_columns",
    "pg_ltree_convert_column",
    "pg_ltree_create_index",
  ],
  introspection: [
    "pg_dependency_graph",
    "pg_topological_sort",
    "pg_cascade_simulator",
    "pg_schema_snapshot",
    "pg_constraint_analysis",
    "pg_migration_risks",
  ],
  migration: [
    "pg_migration_init",
    "pg_migration_record",
    "pg_migration_apply",
    "pg_migration_rollback",
    "pg_migration_history",
    "pg_migration_status",
  ],
  pgcrypto: [
    "pg_pgcrypto_create_extension",
    "pg_pgcrypto_hash",
    "pg_pgcrypto_hmac",
    "pg_pgcrypto_encrypt",
    "pg_pgcrypto_decrypt",
    "pg_pgcrypto_gen_random_uuid",
    "pg_pgcrypto_gen_random_bytes",
    "pg_pgcrypto_gen_salt",
    "pg_pgcrypto_crypt",
  ],
  codemode: ["pg_execute_code"],
};
