/**
 * Generates src/constants/ServerInstructions.ts from src/constants/server-instructions.md
 *
 * Reads the plain markdown source file, escapes backticks and template expressions,
 * and wraps the content in a TypeScript template literal export.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

const mdPath = resolve(projectRoot, "src/constants/server-instructions.md");
const tsPath = resolve(projectRoot, "src/constants/ServerInstructions.ts");

// Read plain markdown source
const markdown = readFileSync(mdPath, "utf-8");

// Escape for template literal: backticks and ${
const escaped = markdown
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

// Build the TypeScript file
const tsContent = `/**
 * Server instructions for Code Mode usage.
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions.md instead,
 *     then run: npm run generate:instructions
 *
 * These instructions are automatically sent to MCP clients during initialization,
 * eliminating the need for users to manually provide agent instructions.
 *
 * Optimized for LLM consumption using the "Just Work" documentation pattern:
 * - Priority-based hierarchy (critical gotchas first)
 * - Removed redundant alias documentation (already in tool schemas)
 * - Semantic tagging for high-signal guidance
 */
export const SERVER_INSTRUCTIONS = \`${escaped}\`;
`;

writeFileSync(tsPath, tsContent, "utf-8");

process.stderr.write(
  `✅ Generated ServerInstructions.ts (${tsContent.length.toLocaleString()} bytes) from server-instructions.md (${markdown.length.toLocaleString()} bytes)\n`,
);
