/**
 * Generates src/constants/server-instructions.ts from per-group markdown files.
 *
 * Reads server-instructions/*.md, escapes for template literals, and wraps them
 * in a TypeScript module with a slim INSTRUCTIONS constant and a HELP_CONTENT map.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const constantsDir = resolve(projectRoot, "src/constants");
const helpDir = resolve(constantsDir, "server-instructions");

/**
 * Escape content for use inside a JS/TS template literal.
 * Handles: backslashes, backticks, and template expressions (${).
 */
function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

// Read overview (slim instructions field content)
const overviewMd = readFileSync(resolve(helpDir, "overview.md"), "utf-8").trim();
const overviewEscaped = escapeForTemplateLiteral(overviewMd);

// Read all help files (everything except overview.md)
const helpFiles = readdirSync(helpDir)
  .filter((f) => f.endsWith(".md") && f !== "overview.md")
  .sort();

const helpEntries: { key: string; content: string }[] = [];
for (const file of helpFiles) {
  const key = basename(file, ".md"); // "gotchas", "jsonb", "stats", etc.
  const content = readFileSync(resolve(helpDir, file), "utf-8").trim();
  helpEntries.push({ key, content });
}

// Use backtick char for building string to avoid nesting issues
const BT = "`";

// Build the TypeScript file using string concatenation
const lines: string[] = [];

lines.push("/**");
lines.push(" * Server instructions for postgres-mcp (PostgreSQL MCP Server).");
lines.push(" *");
lines.push(
  " * \u26a0\ufe0f  AUTO-GENERATED \u2014 DO NOT EDIT THIS FILE DIRECTLY",
);
lines.push(" *     Edit src/constants/server-instructions/*.md instead,");
lines.push(" *     then run: npm run generate:instructions");
lines.push(" *");
lines.push(
  " * Slim instructions are sent to MCP clients during initialization.",
);
lines.push(
  " * Detailed help is available on-demand via postgres://help resources.",
);
lines.push(" */");
lines.push("");
lines.push("/**");
lines.push(" * Slim instructions for the MCP instructions field (~600 chars).");
lines.push(
  " * Points agents to postgres://help resources for detailed reference.",
);
lines.push(" */");
lines.push(
  "export const INSTRUCTIONS = " + BT + overviewEscaped + BT + ";",
);
lines.push("");
lines.push("/**");
lines.push(" * Help content keyed by group name.");
lines.push(
  " * 'gotchas' is the always-available help (postgres://help).",
);
lines.push(
  " * Other keys are tool groups (postgres://help/{group}).",
);
lines.push(" */");
lines.push(
  "export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([",
);
for (const { key, content } of helpEntries) {
  const escaped = escapeForTemplateLiteral(content);
  lines.push("  [" + JSON.stringify(key) + ", " + BT + escaped + BT + "],");
}
lines.push("]);");
lines.push("");

const tsContent = lines.join("\n");
const tsPath = resolve(constantsDir, "server-instructions.ts");
writeFileSync(tsPath, tsContent, "utf-8");

process.stderr.write(
  [
    "",
    "\u2705 Generated server-instructions.ts (" +
      tsContent.length.toLocaleString() +
      " bytes) from " +
      (helpEntries.length + 1) +
      " markdown files",
    "   Overview: " + overviewMd.length.toLocaleString() + " chars",
    "   Help entries: " + helpEntries.map((e) => e.key).join(", "),
    "",
  ].join("\n"),
);
