/**
 * Generates src/constants/ServerInstructions.ts from server-instructions.md
 *
 * Reads the markdown source, splits by GROUP markers
 * (<!-- GROUP: groupname -->), escapes for template literals, and wraps them
 * in a TypeScript module with per-group sections and dynamic filtering.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const constantsDir = resolve(projectRoot, "src/constants");

const sourceFile = resolve(constantsDir, "server-instructions.md");
const sourceMd = readFileSync(sourceFile, "utf-8");

// Parse GROUP markers: <!-- GROUP: groupname -->
const groupPattern = /<!--\s*GROUP:\s*([\w_-]+)\s*-->/g;
const groupMarkers: { name: string; index: number }[] = [];

let match: RegExpExecArray | null;
while ((match = groupPattern.exec(sourceMd)) !== null) {
  groupMarkers.push({ name: match[1], index: match.index + match[0].length });
}

// Extract per-group content
const rawSections: { group: string; content: string }[] = [];
for (let i = 0; i < groupMarkers.length; i++) {
  const start = groupMarkers[i].index;
  const end =
    i + 1 < groupMarkers.length
      ? sourceMd.lastIndexOf("<!--", groupMarkers[i + 1].index)
      : sourceMd.length;
  const content = sourceMd.substring(start, end).trim();
  if (content) {
    rawSections.push({ group: groupMarkers[i].name, content });
  }
}

// Merge sections with the same group name (e.g., text appears twice, _always appears twice)
const mergedSections = new Map<string, string>();
for (const { group, content } of rawSections) {
  const existing = mergedSections.get(group);
  mergedSections.set(group, existing ? existing + "\n\n" + content : content);
}

/**
 * Escape content for use inside a JS/TS template literal.
 */
function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

const BT = "`";

// Build the TypeScript file
const lines: string[] = [];

lines.push("/**");
lines.push(" * Server instructions for postgres-mcp.");
lines.push(" *");
lines.push(
  " * \u26a0\ufe0f  AUTO-GENERATED \u2014 DO NOT EDIT THIS FILE DIRECTLY",
);
lines.push(" *     Edit src/constants/server-instructions.md instead,");
lines.push(" *     then run: npm run generate:instructions");
lines.push(" *");
lines.push(
  " * These instructions are automatically sent to MCP clients during initialization,",
);
lines.push(" * providing guidance for AI agents on tool usage.");
lines.push(" */");
lines.push("");
lines.push('import type { ToolGroup } from "../types/index.js";');
lines.push(
  'import { TOOL_GROUPS } from "../filtering/ToolFilter.js";',
);
lines.push("");

// Emit per-group reference sections as a Map
lines.push("/**");
lines.push(" * Instruction sections keyed by group name.");
lines.push(
  " * '_always' sections are included regardless of tool filter.",
);
lines.push(
  " * Other keys correspond to tool group names from ToolConstants.ts.",
);
lines.push(" */");
lines.push(
  "const INSTRUCTION_SECTIONS: ReadonlyMap<string, string> = new Map([",
);
for (const [group, content] of mergedSections) {
  const escaped = escapeForTemplateLiteral(content);
  lines.push(
    "  [" + JSON.stringify(group) + ", " + BT + "\\n" + escaped + BT + "],",
  );
}
lines.push("]);");
lines.push("");

// Generate the generateInstructions function
lines.push("/**");
lines.push(
  " * Generate dynamic instructions filtered by enabled tool groups.",
);
lines.push(" *");
lines.push(
  " * Derives enabled groups from the enabledTools set, then includes only",
);
lines.push(
  " * instruction sections for those groups (plus '_always' sections).",
);
lines.push(" *");
lines.push(
  " * @param enabledTools - Set of enabled tool names from ToolFilterConfig",
);
lines.push(" */");
lines.push("export function generateInstructions(");
lines.push("  enabledTools: Set<string>,");
lines.push("): string {");
lines.push("  // Derive enabled groups from the enabled tool names");
lines.push("  const enabledGroups = new Set<string>();");
lines.push(
  "  for (const [group, tools] of Object.entries(TOOL_GROUPS) as [ToolGroup, string[]][]) {",
);
lines.push(
  "    if (tools.some((tool) => enabledTools.has(tool))) {",
);
lines.push("      enabledGroups.add(group);");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push(
  "  // Build instructions from _always sections + enabled group sections",
);
lines.push("  let instructions = '';");
lines.push("  for (const [group, content] of INSTRUCTION_SECTIONS) {");
lines.push(
  '    if (group === "_always" || enabledGroups.has(group)) {',
);
lines.push("      instructions += content;");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  return instructions;");
lines.push("}");
lines.push("");

// Backward compat static export
lines.push("/**");
lines.push(" * Static instructions (all sections, unfiltered)");
lines.push(
  " * @deprecated Use generateInstructions() for filtered content",
);
lines.push(" */");
lines.push("export const SERVER_INSTRUCTIONS = (() => {");
lines.push("  let all = '';");
lines.push("  for (const content of INSTRUCTION_SECTIONS.values()) {");
lines.push("    all += content;");
lines.push("  }");
lines.push("  return all;");
lines.push("})();");
lines.push("");

const tsContent = lines.join("\n");
const tsPath = resolve(constantsDir, "ServerInstructions.ts");
writeFileSync(tsPath, tsContent, "utf-8");

process.stderr.write(
  [
    "",
    "\u2705 Generated ServerInstructions.ts (" +
      tsContent.length.toLocaleString() +
      " bytes) from server-instructions.md (" +
      sourceMd.length.toLocaleString() +
      " bytes)",
    "   " +
      mergedSections.size +
      " unique groups (" +
      [...mergedSections.keys()].join(", ") +
      ")",
    "",
  ].join("\n"),
);
