# act -W ../.github/workflows/docker-build-dockerhub.yml -s DOCKERHUB_USERNAME -s DOCKERHUB_TOKEN -s GITHUB_TOKEN="$(gh auth token)"
---
name: Build and Push Docker Image to DockerHub

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (without v prefix)"
        required: true
        default: ""

# Security: Explicit permissions following principle of least privilege
permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.VERSION }}
    steps:
      - name: Set version from tag
        id: set-version
        run: |
          if [[ "${{ github.event_name }}" == "push" && \
                "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:latest

      - name: Inspect builder
        run: |
          echo "Available platforms: $(docker buildx inspect --bootstrap | grep 'Platforms:')"
          docker buildx ls

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
          image: tonistiigi/binfmt:latest

      - name: Prepare Docker tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: writenotenow/postgres-mcp-enhanced
          flavor: |
            latest=auto
          tags: |
            # Always create latest tag for tag pushes
            type=raw,value=latest
            # Create version tags (v1.0.3)
            type=raw,value=v${{ needs.prepare.outputs.version }}
            # Create short SHA tags for all builds (e.g., sha-a317583)
            type=sha,prefix=sha-
            # Create timestamped master branch tags (e.g., master-20251003-161652-a317583)
            type=sha,prefix=master-{{date 'YYYYMMDD-HHmmss'}}-

      - name: Check directory structure
        run: |
          echo "check pwd: $(pwd)"
          echo "check ls: $(ls -lta)"

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          # Use GitHub Actions cache instead of registry cache to avoid buildcache tag
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Security: Enable build attestations for supply chain security
          provenance: mode=max
          sbom: true
      
      - name: Docker Scout Analysis
        uses: docker/scout-action@v1
        if: github.event_name == 'push'
        with:
          command: cves,recommendations
          image: writenotenow/postgres-mcp-enhanced:v${{ needs.prepare.outputs.version }}
          only-severities: critical,high
          exit-code: false
          write-comment: true
      
      - name: Docker Scout Compare
        uses: docker/scout-action@v1
        if: github.event_name == 'push'
        with:
          command: compare
          image: writenotenow/postgres-mcp-enhanced:v${{ needs.prepare.outputs.version }}
          to: writenotenow/postgres-mcp-enhanced:latest
          exit-code: false
      
      - name: Update Docker Hub Description
        if: github.event_name == 'push'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: writenotenow/postgres-mcp-enhanced
          readme-filepath: ./DOCKER_README.md
          short-description: "Enterprise PostgreSQL MCP Server - 63 specialized tools with comprehensive security and AI-native operations"
